/*
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file was automatically generated by the code_generation module.
 * Any changes made to this file will be lost when regenerated.
 *
 * To modify this file, edit the corresponding template in:
 * code_generation/templates/extensions/enabled_extensions.mako
 */
// SPDX-License-Identifier: LGPL-3.0-or-later

#ifndef XRTRANSPORT_ENABLED_EXTENSIONS_H
#define XRTRANSPORT_ENABLED_EXTENSIONS_H

#include <unordered_map>
#include <string>
#include <cstdint>

namespace xrtransport {

// Map of extension name to extension version
static const std::unordered_map<std::string, std::uint32_t> enabled_extensions = {
#ifdef XRTRANSPORT_EXT_XR_ALMALENCE_digital_lens_control
    {"XR_ALMALENCE_digital_lens_control", XR_ALMALENCE_digital_lens_control_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_ALMALENCE_digital_lens_control
#ifdef XRTRANSPORT_EXT_XR_BD_body_tracking
    {"XR_BD_body_tracking", XR_BD_body_tracking_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_BD_body_tracking
#ifdef XRTRANSPORT_EXT_XR_BD_future_progress
    {"XR_BD_future_progress", XR_BD_future_progress_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_BD_future_progress
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_anchor
    {"XR_BD_spatial_anchor", XR_BD_spatial_anchor_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_anchor
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_anchor_sharing
    {"XR_BD_spatial_anchor_sharing", XR_BD_spatial_anchor_sharing_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_anchor_sharing
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_mesh
    {"XR_BD_spatial_mesh", XR_BD_spatial_mesh_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_mesh
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_scene
    {"XR_BD_spatial_scene", XR_BD_spatial_scene_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_scene
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_sensing
    {"XR_BD_spatial_sensing", XR_BD_spatial_sensing_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_sensing
#ifdef XRTRANSPORT_EXT_XR_EPIC_view_configuration_fov
    {"XR_EPIC_view_configuration_fov", XR_EPIC_view_configuration_fov_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EPIC_view_configuration_fov
#ifdef XRTRANSPORT_EXT_XR_EXTX_overlay
    {"XR_EXTX_overlay", XR_EXTX_overlay_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXTX_overlay
#ifdef XRTRANSPORT_EXT_XR_EXT_active_action_set_priority
    {"XR_EXT_active_action_set_priority", XR_EXT_active_action_set_priority_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_active_action_set_priority
#ifdef XRTRANSPORT_EXT_XR_EXT_conformance_automation
    {"XR_EXT_conformance_automation", XR_EXT_conformance_automation_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_conformance_automation
#ifdef XRTRANSPORT_EXT_XR_EXT_debug_utils
    {"XR_EXT_debug_utils", XR_EXT_debug_utils_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_debug_utils
#ifdef XRTRANSPORT_EXT_XR_EXT_dpad_binding
    {"XR_EXT_dpad_binding", XR_EXT_dpad_binding_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_dpad_binding
#ifdef XRTRANSPORT_EXT_XR_EXT_eye_gaze_interaction
    {"XR_EXT_eye_gaze_interaction", XR_EXT_eye_gaze_interaction_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_eye_gaze_interaction
#ifdef XRTRANSPORT_EXT_XR_EXT_frame_synthesis
    {"XR_EXT_frame_synthesis", XR_EXT_frame_synthesis_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_frame_synthesis
#ifdef XRTRANSPORT_EXT_XR_EXT_future
    {"XR_EXT_future", XR_EXT_future_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_future
#ifdef XRTRANSPORT_EXT_XR_EXT_hand_joints_motion_range
    {"XR_EXT_hand_joints_motion_range", XR_EXT_hand_joints_motion_range_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_hand_joints_motion_range
#ifdef XRTRANSPORT_EXT_XR_EXT_hand_tracking
    {"XR_EXT_hand_tracking", XR_EXT_hand_tracking_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_hand_tracking
#ifdef XRTRANSPORT_EXT_XR_EXT_hand_tracking_data_source
    {"XR_EXT_hand_tracking_data_source", XR_EXT_hand_tracking_data_source_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_hand_tracking_data_source
#ifdef XRTRANSPORT_EXT_XR_EXT_performance_settings
    {"XR_EXT_performance_settings", XR_EXT_performance_settings_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_performance_settings
#ifdef XRTRANSPORT_EXT_XR_EXT_plane_detection
    {"XR_EXT_plane_detection", XR_EXT_plane_detection_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_plane_detection
#ifdef XRTRANSPORT_EXT_XR_EXT_thermal_query
    {"XR_EXT_thermal_query", XR_EXT_thermal_query_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_thermal_query
#ifdef XRTRANSPORT_EXT_XR_EXT_user_presence
    {"XR_EXT_user_presence", XR_EXT_user_presence_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_user_presence
#ifdef XRTRANSPORT_EXT_XR_EXT_view_configuration_depth_range
    {"XR_EXT_view_configuration_depth_range", XR_EXT_view_configuration_depth_range_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_EXT_view_configuration_depth_range
#ifdef XRTRANSPORT_EXT_XR_FB_android_surface_swapchain_create
    {"XR_FB_android_surface_swapchain_create", XR_FB_android_surface_swapchain_create_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_android_surface_swapchain_create
#ifdef XRTRANSPORT_EXT_XR_FB_body_tracking
    {"XR_FB_body_tracking", XR_FB_body_tracking_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_body_tracking
#ifdef XRTRANSPORT_EXT_XR_FB_color_space
    {"XR_FB_color_space", XR_FB_color_space_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_color_space
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_alpha_blend
    {"XR_FB_composition_layer_alpha_blend", XR_FB_composition_layer_alpha_blend_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_alpha_blend
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_depth_test
    {"XR_FB_composition_layer_depth_test", XR_FB_composition_layer_depth_test_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_depth_test
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_image_layout
    {"XR_FB_composition_layer_image_layout", XR_FB_composition_layer_image_layout_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_image_layout
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_secure_content
    {"XR_FB_composition_layer_secure_content", XR_FB_composition_layer_secure_content_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_secure_content
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_settings
    {"XR_FB_composition_layer_settings", XR_FB_composition_layer_settings_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_settings
#ifdef XRTRANSPORT_EXT_XR_FB_display_refresh_rate
    {"XR_FB_display_refresh_rate", XR_FB_display_refresh_rate_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_display_refresh_rate
#ifdef XRTRANSPORT_EXT_XR_FB_eye_tracking_social
    {"XR_FB_eye_tracking_social", XR_FB_eye_tracking_social_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_eye_tracking_social
#ifdef XRTRANSPORT_EXT_XR_FB_face_tracking
    {"XR_FB_face_tracking", XR_FB_face_tracking_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_face_tracking
#ifdef XRTRANSPORT_EXT_XR_FB_face_tracking2
    {"XR_FB_face_tracking2", XR_FB_face_tracking2_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_face_tracking2
#ifdef XRTRANSPORT_EXT_XR_FB_foveation
    {"XR_FB_foveation", XR_FB_foveation_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_foveation
#ifdef XRTRANSPORT_EXT_XR_FB_foveation_configuration
    {"XR_FB_foveation_configuration", XR_FB_foveation_configuration_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_foveation_configuration
#ifdef XRTRANSPORT_EXT_XR_FB_foveation_vulkan
    {"XR_FB_foveation_vulkan", XR_FB_foveation_vulkan_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_foveation_vulkan
#ifdef XRTRANSPORT_EXT_XR_FB_hand_tracking_aim
    {"XR_FB_hand_tracking_aim", XR_FB_hand_tracking_aim_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_hand_tracking_aim
#ifdef XRTRANSPORT_EXT_XR_FB_hand_tracking_capsules
    {"XR_FB_hand_tracking_capsules", XR_FB_hand_tracking_capsules_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_hand_tracking_capsules
#ifdef XRTRANSPORT_EXT_XR_FB_hand_tracking_mesh
    {"XR_FB_hand_tracking_mesh", XR_FB_hand_tracking_mesh_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_hand_tracking_mesh
#ifdef XRTRANSPORT_EXT_XR_FB_haptic_amplitude_envelope
    {"XR_FB_haptic_amplitude_envelope", XR_FB_haptic_amplitude_envelope_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_haptic_amplitude_envelope
#ifdef XRTRANSPORT_EXT_XR_FB_haptic_pcm
    {"XR_FB_haptic_pcm", XR_FB_haptic_pcm_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_haptic_pcm
#ifdef XRTRANSPORT_EXT_XR_FB_keyboard_tracking
    {"XR_FB_keyboard_tracking", XR_FB_keyboard_tracking_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_keyboard_tracking
#ifdef XRTRANSPORT_EXT_XR_FB_passthrough
    {"XR_FB_passthrough", XR_FB_passthrough_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_passthrough
#ifdef XRTRANSPORT_EXT_XR_FB_passthrough_keyboard_hands
    {"XR_FB_passthrough_keyboard_hands", XR_FB_passthrough_keyboard_hands_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_passthrough_keyboard_hands
#ifdef XRTRANSPORT_EXT_XR_FB_render_model
    {"XR_FB_render_model", XR_FB_render_model_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_render_model
#ifdef XRTRANSPORT_EXT_XR_FB_scene
    {"XR_FB_scene", XR_FB_scene_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_scene
#ifdef XRTRANSPORT_EXT_XR_FB_scene_capture
    {"XR_FB_scene_capture", XR_FB_scene_capture_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_scene_capture
#ifdef XRTRANSPORT_EXT_XR_FB_space_warp
    {"XR_FB_space_warp", XR_FB_space_warp_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_space_warp
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity
    {"XR_FB_spatial_entity", XR_FB_spatial_entity_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_container
    {"XR_FB_spatial_entity_container", XR_FB_spatial_entity_container_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_container
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_query
    {"XR_FB_spatial_entity_query", XR_FB_spatial_entity_query_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_query
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_sharing
    {"XR_FB_spatial_entity_sharing", XR_FB_spatial_entity_sharing_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_sharing
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_storage
    {"XR_FB_spatial_entity_storage", XR_FB_spatial_entity_storage_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_storage
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_storage_batch
    {"XR_FB_spatial_entity_storage_batch", XR_FB_spatial_entity_storage_batch_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_storage_batch
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_user
    {"XR_FB_spatial_entity_user", XR_FB_spatial_entity_user_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_user
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state
    {"XR_FB_swapchain_update_state", XR_FB_swapchain_update_state_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state_android_surface
    {"XR_FB_swapchain_update_state_android_surface", XR_FB_swapchain_update_state_android_surface_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state_android_surface
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state_opengl_es
    {"XR_FB_swapchain_update_state_opengl_es", XR_FB_swapchain_update_state_opengl_es_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state_opengl_es
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state_vulkan
    {"XR_FB_swapchain_update_state_vulkan", XR_FB_swapchain_update_state_vulkan_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state_vulkan
#ifdef XRTRANSPORT_EXT_XR_FB_triangle_mesh
    {"XR_FB_triangle_mesh", XR_FB_triangle_mesh_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_FB_triangle_mesh
#ifdef XRTRANSPORT_EXT_XR_HTCX_vive_tracker_interaction
    {"XR_HTCX_vive_tracker_interaction", XR_HTCX_vive_tracker_interaction_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_HTCX_vive_tracker_interaction
#ifdef XRTRANSPORT_EXT_XR_HTC_anchor
    {"XR_HTC_anchor", XR_HTC_anchor_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_HTC_anchor
#ifdef XRTRANSPORT_EXT_XR_HTC_body_tracking
    {"XR_HTC_body_tracking", XR_HTC_body_tracking_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_HTC_body_tracking
#ifdef XRTRANSPORT_EXT_XR_HTC_facial_tracking
    {"XR_HTC_facial_tracking", XR_HTC_facial_tracking_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_HTC_facial_tracking
#ifdef XRTRANSPORT_EXT_XR_HTC_foveation
    {"XR_HTC_foveation", XR_HTC_foveation_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_HTC_foveation
#ifdef XRTRANSPORT_EXT_XR_HTC_passthrough
    {"XR_HTC_passthrough", XR_HTC_passthrough_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_HTC_passthrough
#ifdef XRTRANSPORT_EXT_XR_KHR_D3D11_enable
    {"XR_KHR_D3D11_enable", XR_KHR_D3D11_enable_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_D3D11_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_D3D12_enable
    {"XR_KHR_D3D12_enable", XR_KHR_D3D12_enable_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_D3D12_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_android_create_instance
    {"XR_KHR_android_create_instance", XR_KHR_android_create_instance_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_android_create_instance
#ifdef XRTRANSPORT_EXT_XR_KHR_android_surface_swapchain
    {"XR_KHR_android_surface_swapchain", XR_KHR_android_surface_swapchain_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_android_surface_swapchain
#ifdef XRTRANSPORT_EXT_XR_KHR_android_thread_settings
    {"XR_KHR_android_thread_settings", XR_KHR_android_thread_settings_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_android_thread_settings
#ifdef XRTRANSPORT_EXT_XR_KHR_binding_modification
    {"XR_KHR_binding_modification", XR_KHR_binding_modification_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_binding_modification
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_color_scale_bias
    {"XR_KHR_composition_layer_color_scale_bias", XR_KHR_composition_layer_color_scale_bias_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_color_scale_bias
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_cube
    {"XR_KHR_composition_layer_cube", XR_KHR_composition_layer_cube_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_cube
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_cylinder
    {"XR_KHR_composition_layer_cylinder", XR_KHR_composition_layer_cylinder_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_cylinder
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_depth
    {"XR_KHR_composition_layer_depth", XR_KHR_composition_layer_depth_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_depth
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_equirect
    {"XR_KHR_composition_layer_equirect", XR_KHR_composition_layer_equirect_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_equirect
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_equirect2
    {"XR_KHR_composition_layer_equirect2", XR_KHR_composition_layer_equirect2_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_equirect2
#ifdef XRTRANSPORT_EXT_XR_KHR_convert_timespec_time
    {"XR_KHR_convert_timespec_time", XR_KHR_convert_timespec_time_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_convert_timespec_time
#ifdef XRTRANSPORT_EXT_XR_KHR_extended_struct_name_lengths
    {"XR_KHR_extended_struct_name_lengths", XR_KHR_extended_struct_name_lengths_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_extended_struct_name_lengths
#ifdef XRTRANSPORT_EXT_XR_KHR_loader_init
    {"XR_KHR_loader_init", XR_KHR_loader_init_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_loader_init
#ifdef XRTRANSPORT_EXT_XR_KHR_loader_init_android
    {"XR_KHR_loader_init_android", XR_KHR_loader_init_android_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_loader_init_android
#ifdef XRTRANSPORT_EXT_XR_KHR_metal_enable
    {"XR_KHR_metal_enable", XR_KHR_metal_enable_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_metal_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_opengl_enable
    {"XR_KHR_opengl_enable", XR_KHR_opengl_enable_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_opengl_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_opengl_es_enable
    {"XR_KHR_opengl_es_enable", XR_KHR_opengl_es_enable_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_opengl_es_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_visibility_mask
    {"XR_KHR_visibility_mask", XR_KHR_visibility_mask_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_visibility_mask
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_enable
    {"XR_KHR_vulkan_enable", XR_KHR_vulkan_enable_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_enable2
    {"XR_KHR_vulkan_enable2", XR_KHR_vulkan_enable2_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_enable2
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_swapchain_format_list
    {"XR_KHR_vulkan_swapchain_format_list", XR_KHR_vulkan_swapchain_format_list_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_swapchain_format_list
#ifdef XRTRANSPORT_EXT_XR_KHR_win32_convert_performance_counter_time
    {"XR_KHR_win32_convert_performance_counter_time", XR_KHR_win32_convert_performance_counter_time_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_KHR_win32_convert_performance_counter_time
#ifdef XRTRANSPORT_EXT_XR_META_body_tracking_full_body
    {"XR_META_body_tracking_full_body", XR_META_body_tracking_full_body_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_body_tracking_full_body
#ifdef XRTRANSPORT_EXT_XR_META_colocation_discovery
    {"XR_META_colocation_discovery", XR_META_colocation_discovery_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_colocation_discovery
#ifdef XRTRANSPORT_EXT_XR_META_environment_depth
    {"XR_META_environment_depth", XR_META_environment_depth_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_environment_depth
#ifdef XRTRANSPORT_EXT_XR_META_foveation_eye_tracked
    {"XR_META_foveation_eye_tracked", XR_META_foveation_eye_tracked_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_foveation_eye_tracked
#ifdef XRTRANSPORT_EXT_XR_META_headset_id
    {"XR_META_headset_id", XR_META_headset_id_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_headset_id
#ifdef XRTRANSPORT_EXT_XR_META_local_dimming
    {"XR_META_local_dimming", XR_META_local_dimming_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_local_dimming
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_color_lut
    {"XR_META_passthrough_color_lut", XR_META_passthrough_color_lut_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_passthrough_color_lut
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_layer_resumed_event
    {"XR_META_passthrough_layer_resumed_event", XR_META_passthrough_layer_resumed_event_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_passthrough_layer_resumed_event
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_preferences
    {"XR_META_passthrough_preferences", XR_META_passthrough_preferences_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_passthrough_preferences
#ifdef XRTRANSPORT_EXT_XR_META_performance_metrics
    {"XR_META_performance_metrics", XR_META_performance_metrics_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_performance_metrics
#ifdef XRTRANSPORT_EXT_XR_META_recommended_layer_resolution
    {"XR_META_recommended_layer_resolution", XR_META_recommended_layer_resolution_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_recommended_layer_resolution
#ifdef XRTRANSPORT_EXT_XR_META_simultaneous_hands_and_controllers
    {"XR_META_simultaneous_hands_and_controllers", XR_META_simultaneous_hands_and_controllers_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_simultaneous_hands_and_controllers
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_group_sharing
    {"XR_META_spatial_entity_group_sharing", XR_META_spatial_entity_group_sharing_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_group_sharing
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_mesh
    {"XR_META_spatial_entity_mesh", XR_META_spatial_entity_mesh_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_mesh
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_sharing
    {"XR_META_spatial_entity_sharing", XR_META_spatial_entity_sharing_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_sharing
#ifdef XRTRANSPORT_EXT_XR_META_virtual_keyboard
    {"XR_META_virtual_keyboard", XR_META_virtual_keyboard_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_virtual_keyboard
#ifdef XRTRANSPORT_EXT_XR_META_vulkan_swapchain_create_info
    {"XR_META_vulkan_swapchain_create_info", XR_META_vulkan_swapchain_create_info_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_META_vulkan_swapchain_create_info
#ifdef XRTRANSPORT_EXT_XR_ML_compat
    {"XR_ML_compat", XR_ML_compat_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_ML_compat
#ifdef XRTRANSPORT_EXT_XR_ML_facial_expression
    {"XR_ML_facial_expression", XR_ML_facial_expression_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_ML_facial_expression
#ifdef XRTRANSPORT_EXT_XR_ML_frame_end_info
    {"XR_ML_frame_end_info", XR_ML_frame_end_info_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_ML_frame_end_info
#ifdef XRTRANSPORT_EXT_XR_ML_global_dimmer
    {"XR_ML_global_dimmer", XR_ML_global_dimmer_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_ML_global_dimmer
#ifdef XRTRANSPORT_EXT_XR_ML_localization_map
    {"XR_ML_localization_map", XR_ML_localization_map_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_ML_localization_map
#ifdef XRTRANSPORT_EXT_XR_ML_marker_understanding
    {"XR_ML_marker_understanding", XR_ML_marker_understanding_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_ML_marker_understanding
#ifdef XRTRANSPORT_EXT_XR_ML_spatial_anchors
    {"XR_ML_spatial_anchors", XR_ML_spatial_anchors_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_ML_spatial_anchors
#ifdef XRTRANSPORT_EXT_XR_ML_spatial_anchors_storage
    {"XR_ML_spatial_anchors_storage", XR_ML_spatial_anchors_storage_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_ML_spatial_anchors_storage
#ifdef XRTRANSPORT_EXT_XR_ML_system_notifications
    {"XR_ML_system_notifications", XR_ML_system_notifications_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_ML_system_notifications
#ifdef XRTRANSPORT_EXT_XR_ML_user_calibration
    {"XR_ML_user_calibration", XR_ML_user_calibration_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_ML_user_calibration
#ifdef XRTRANSPORT_EXT_XR_ML_world_mesh_detection
    {"XR_ML_world_mesh_detection", XR_ML_world_mesh_detection_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_ML_world_mesh_detection
#ifdef XRTRANSPORT_EXT_XR_MNDX_egl_enable
    {"XR_MNDX_egl_enable", XR_MNDX_egl_enable_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MNDX_egl_enable
#ifdef XRTRANSPORT_EXT_XR_MNDX_force_feedback_curl
    {"XR_MNDX_force_feedback_curl", XR_MNDX_force_feedback_curl_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MNDX_force_feedback_curl
#ifdef XRTRANSPORT_EXT_XR_MSFT_composition_layer_reprojection
    {"XR_MSFT_composition_layer_reprojection", XR_MSFT_composition_layer_reprojection_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MSFT_composition_layer_reprojection
#ifdef XRTRANSPORT_EXT_XR_MSFT_controller_model
    {"XR_MSFT_controller_model", XR_MSFT_controller_model_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MSFT_controller_model
#ifdef XRTRANSPORT_EXT_XR_MSFT_hand_tracking_mesh
    {"XR_MSFT_hand_tracking_mesh", XR_MSFT_hand_tracking_mesh_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MSFT_hand_tracking_mesh
#ifdef XRTRANSPORT_EXT_XR_MSFT_holographic_window_attachment
    {"XR_MSFT_holographic_window_attachment", XR_MSFT_holographic_window_attachment_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MSFT_holographic_window_attachment
#ifdef XRTRANSPORT_EXT_XR_MSFT_perception_anchor_interop
    {"XR_MSFT_perception_anchor_interop", XR_MSFT_perception_anchor_interop_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MSFT_perception_anchor_interop
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_marker
    {"XR_MSFT_scene_marker", XR_MSFT_scene_marker_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_marker
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_understanding
    {"XR_MSFT_scene_understanding", XR_MSFT_scene_understanding_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_understanding
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_understanding_serialization
    {"XR_MSFT_scene_understanding_serialization", XR_MSFT_scene_understanding_serialization_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_understanding_serialization
#ifdef XRTRANSPORT_EXT_XR_MSFT_secondary_view_configuration
    {"XR_MSFT_secondary_view_configuration", XR_MSFT_secondary_view_configuration_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MSFT_secondary_view_configuration
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_anchor
    {"XR_MSFT_spatial_anchor", XR_MSFT_spatial_anchor_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_anchor
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_anchor_persistence
    {"XR_MSFT_spatial_anchor_persistence", XR_MSFT_spatial_anchor_persistence_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_anchor_persistence
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_graph_bridge
    {"XR_MSFT_spatial_graph_bridge", XR_MSFT_spatial_graph_bridge_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_graph_bridge
#ifdef XRTRANSPORT_EXT_XR_OCULUS_audio_device_guid
    {"XR_OCULUS_audio_device_guid", XR_OCULUS_audio_device_guid_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_OCULUS_audio_device_guid
#ifdef XRTRANSPORT_EXT_XR_OCULUS_external_camera
    {"XR_OCULUS_external_camera", XR_OCULUS_external_camera_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_OCULUS_external_camera
#ifdef XRTRANSPORT_EXT_XR_QCOM_tracking_optimization_settings
    {"XR_QCOM_tracking_optimization_settings", XR_QCOM_tracking_optimization_settings_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_QCOM_tracking_optimization_settings
#ifdef XRTRANSPORT_EXT_XR_VALVE_analog_threshold
    {"XR_VALVE_analog_threshold", XR_VALVE_analog_threshold_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_VALVE_analog_threshold
#ifdef XRTRANSPORT_EXT_XR_VARJO_composition_layer_depth_test
    {"XR_VARJO_composition_layer_depth_test", XR_VARJO_composition_layer_depth_test_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_VARJO_composition_layer_depth_test
#ifdef XRTRANSPORT_EXT_XR_VARJO_environment_depth_estimation
    {"XR_VARJO_environment_depth_estimation", XR_VARJO_environment_depth_estimation_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_VARJO_environment_depth_estimation
#ifdef XRTRANSPORT_EXT_XR_VARJO_foveated_rendering
    {"XR_VARJO_foveated_rendering", XR_VARJO_foveated_rendering_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_VARJO_foveated_rendering
#ifdef XRTRANSPORT_EXT_XR_VARJO_marker_tracking
    {"XR_VARJO_marker_tracking", XR_VARJO_marker_tracking_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_VARJO_marker_tracking
#ifdef XRTRANSPORT_EXT_XR_VARJO_view_offset
    {"XR_VARJO_view_offset", XR_VARJO_view_offset_SPEC_VERSION},
#endif // XRTRANSPORT_EXT_XR_VARJO_view_offset
};

} // namespace xrtransport

#endif // XRTRANSPORT_ENABLED_EXTENSIONS_H