/*
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file was automatically generated by the code_generation module.
 * Any changes made to this file will be lost when regenerated.
 *
 * To modify this file, edit the corresponding template in:
 * code_generation/templates/client/function_table_impl.mako
 */
// SPDX-License-Identifier: LGPL-3.0-or-later

#include "function_table.h"
#include "rpc.h"

namespace xrtransport {

void FunctionTable::init_with_rpc_functions() {
#ifdef XRTRANSPORT_EXT_XR_ALMALENCE_digital_lens_control
    table.emplace("xrSetDigitalLensControlALMALENCE", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetDigitalLensControlALMALENCE));
#endif // XRTRANSPORT_EXT_XR_ALMALENCE_digital_lens_control
#ifdef XRTRANSPORT_EXT_XR_BD_body_tracking
    table.emplace("xrCreateBodyTrackerBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateBodyTrackerBD));
    table.emplace("xrDestroyBodyTrackerBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyBodyTrackerBD));
    table.emplace("xrLocateBodyJointsBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrLocateBodyJointsBD));
#endif // XRTRANSPORT_EXT_XR_BD_body_tracking
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_anchor
    table.emplace("xrCreateSpatialAnchorAsyncBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialAnchorAsyncBD));
    table.emplace("xrCreateSpatialAnchorCompleteBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialAnchorCompleteBD));
    table.emplace("xrPersistSpatialAnchorAsyncBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPersistSpatialAnchorAsyncBD));
    table.emplace("xrPersistSpatialAnchorCompleteBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPersistSpatialAnchorCompleteBD));
    table.emplace("xrUnpersistSpatialAnchorAsyncBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrUnpersistSpatialAnchorAsyncBD));
    table.emplace("xrUnpersistSpatialAnchorCompleteBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrUnpersistSpatialAnchorCompleteBD));
#endif // XRTRANSPORT_EXT_XR_BD_spatial_anchor
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_anchor_sharing
    table.emplace("xrDownloadSharedSpatialAnchorAsyncBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDownloadSharedSpatialAnchorAsyncBD));
    table.emplace("xrDownloadSharedSpatialAnchorCompleteBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDownloadSharedSpatialAnchorCompleteBD));
    table.emplace("xrShareSpatialAnchorAsyncBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrShareSpatialAnchorAsyncBD));
    table.emplace("xrShareSpatialAnchorCompleteBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrShareSpatialAnchorCompleteBD));
#endif // XRTRANSPORT_EXT_XR_BD_spatial_anchor_sharing
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_scene
    table.emplace("xrCaptureSceneAsyncBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCaptureSceneAsyncBD));
    table.emplace("xrCaptureSceneCompleteBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCaptureSceneCompleteBD));
#endif // XRTRANSPORT_EXT_XR_BD_spatial_scene
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_sensing
    table.emplace("xrCreateAnchorSpaceBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateAnchorSpaceBD));
    table.emplace("xrCreateSenseDataProviderBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSenseDataProviderBD));
    table.emplace("xrCreateSpatialEntityAnchorBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialEntityAnchorBD));
    table.emplace("xrDestroyAnchorBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyAnchorBD));
    table.emplace("xrDestroySenseDataProviderBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroySenseDataProviderBD));
    table.emplace("xrDestroySenseDataSnapshotBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroySenseDataSnapshotBD));
    table.emplace("xrEnumerateSpatialEntityComponentTypesBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateSpatialEntityComponentTypesBD));
    table.emplace("xrGetAnchorUuidBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetAnchorUuidBD));
    table.emplace("xrGetQueriedSenseDataBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetQueriedSenseDataBD));
    table.emplace("xrGetSenseDataProviderStateBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSenseDataProviderStateBD));
    table.emplace("xrGetSpatialEntityComponentDataBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpatialEntityComponentDataBD));
    table.emplace("xrGetSpatialEntityUuidBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpatialEntityUuidBD));
    table.emplace("xrQuerySenseDataAsyncBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrQuerySenseDataAsyncBD));
    table.emplace("xrQuerySenseDataCompleteBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrQuerySenseDataCompleteBD));
    table.emplace("xrStartSenseDataProviderAsyncBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStartSenseDataProviderAsyncBD));
    table.emplace("xrStartSenseDataProviderCompleteBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStartSenseDataProviderCompleteBD));
    table.emplace("xrStopSenseDataProviderBD", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStopSenseDataProviderBD));
#endif // XRTRANSPORT_EXT_XR_BD_spatial_sensing
#ifdef XRTRANSPORT_EXT_XR_EXT_conformance_automation
    table.emplace("xrSetInputDeviceActiveEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetInputDeviceActiveEXT));
    table.emplace("xrSetInputDeviceLocationEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetInputDeviceLocationEXT));
    table.emplace("xrSetInputDeviceStateBoolEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetInputDeviceStateBoolEXT));
    table.emplace("xrSetInputDeviceStateFloatEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetInputDeviceStateFloatEXT));
    table.emplace("xrSetInputDeviceStateVector2fEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetInputDeviceStateVector2fEXT));
#endif // XRTRANSPORT_EXT_XR_EXT_conformance_automation
#ifdef XRTRANSPORT_EXT_XR_EXT_debug_utils
    table.emplace("xrCreateDebugUtilsMessengerEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateDebugUtilsMessengerEXT));
    table.emplace("xrDestroyDebugUtilsMessengerEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyDebugUtilsMessengerEXT));
    table.emplace("xrSessionBeginDebugUtilsLabelRegionEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSessionBeginDebugUtilsLabelRegionEXT));
    table.emplace("xrSessionEndDebugUtilsLabelRegionEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSessionEndDebugUtilsLabelRegionEXT));
    table.emplace("xrSessionInsertDebugUtilsLabelEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSessionInsertDebugUtilsLabelEXT));
    table.emplace("xrSetDebugUtilsObjectNameEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetDebugUtilsObjectNameEXT));
    table.emplace("xrSubmitDebugUtilsMessageEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSubmitDebugUtilsMessageEXT));
#endif // XRTRANSPORT_EXT_XR_EXT_debug_utils
#ifdef XRTRANSPORT_EXT_XR_EXT_future
    table.emplace("xrCancelFutureEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCancelFutureEXT));
    table.emplace("xrPollFutureEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPollFutureEXT));
#endif // XRTRANSPORT_EXT_XR_EXT_future
#ifdef XRTRANSPORT_EXT_XR_EXT_hand_tracking
    table.emplace("xrCreateHandTrackerEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateHandTrackerEXT));
    table.emplace("xrDestroyHandTrackerEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyHandTrackerEXT));
    table.emplace("xrLocateHandJointsEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrLocateHandJointsEXT));
#endif // XRTRANSPORT_EXT_XR_EXT_hand_tracking
#ifdef XRTRANSPORT_EXT_XR_EXT_performance_settings
    table.emplace("xrPerfSettingsSetPerformanceLevelEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPerfSettingsSetPerformanceLevelEXT));
#endif // XRTRANSPORT_EXT_XR_EXT_performance_settings
#ifdef XRTRANSPORT_EXT_XR_EXT_plane_detection
    table.emplace("xrBeginPlaneDetectionEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrBeginPlaneDetectionEXT));
    table.emplace("xrCreatePlaneDetectorEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreatePlaneDetectorEXT));
    table.emplace("xrDestroyPlaneDetectorEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyPlaneDetectorEXT));
    table.emplace("xrGetPlaneDetectionStateEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetPlaneDetectionStateEXT));
    table.emplace("xrGetPlaneDetectionsEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetPlaneDetectionsEXT));
    table.emplace("xrGetPlanePolygonBufferEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetPlanePolygonBufferEXT));
#endif // XRTRANSPORT_EXT_XR_EXT_plane_detection
#ifdef XRTRANSPORT_EXT_XR_EXT_thermal_query
    table.emplace("xrThermalGetTemperatureTrendEXT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrThermalGetTemperatureTrendEXT));
#endif // XRTRANSPORT_EXT_XR_EXT_thermal_query
#ifdef XRTRANSPORT_EXT_XR_FB_body_tracking
    table.emplace("xrCreateBodyTrackerFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateBodyTrackerFB));
    table.emplace("xrDestroyBodyTrackerFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyBodyTrackerFB));
    table.emplace("xrGetBodySkeletonFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetBodySkeletonFB));
    table.emplace("xrLocateBodyJointsFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrLocateBodyJointsFB));
#endif // XRTRANSPORT_EXT_XR_FB_body_tracking
#ifdef XRTRANSPORT_EXT_XR_FB_color_space
    table.emplace("xrEnumerateColorSpacesFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateColorSpacesFB));
    table.emplace("xrSetColorSpaceFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetColorSpaceFB));
#endif // XRTRANSPORT_EXT_XR_FB_color_space
#ifdef XRTRANSPORT_EXT_XR_FB_display_refresh_rate
    table.emplace("xrEnumerateDisplayRefreshRatesFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateDisplayRefreshRatesFB));
    table.emplace("xrGetDisplayRefreshRateFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetDisplayRefreshRateFB));
    table.emplace("xrRequestDisplayRefreshRateFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrRequestDisplayRefreshRateFB));
#endif // XRTRANSPORT_EXT_XR_FB_display_refresh_rate
#ifdef XRTRANSPORT_EXT_XR_FB_eye_tracking_social
    table.emplace("xrCreateEyeTrackerFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateEyeTrackerFB));
    table.emplace("xrDestroyEyeTrackerFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyEyeTrackerFB));
    table.emplace("xrGetEyeGazesFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetEyeGazesFB));
#endif // XRTRANSPORT_EXT_XR_FB_eye_tracking_social
#ifdef XRTRANSPORT_EXT_XR_FB_face_tracking
    table.emplace("xrCreateFaceTrackerFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateFaceTrackerFB));
    table.emplace("xrDestroyFaceTrackerFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyFaceTrackerFB));
    table.emplace("xrGetFaceExpressionWeightsFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetFaceExpressionWeightsFB));
#endif // XRTRANSPORT_EXT_XR_FB_face_tracking
#ifdef XRTRANSPORT_EXT_XR_FB_face_tracking2
    table.emplace("xrCreateFaceTracker2FB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateFaceTracker2FB));
    table.emplace("xrDestroyFaceTracker2FB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyFaceTracker2FB));
    table.emplace("xrGetFaceExpressionWeights2FB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetFaceExpressionWeights2FB));
#endif // XRTRANSPORT_EXT_XR_FB_face_tracking2
#ifdef XRTRANSPORT_EXT_XR_FB_foveation
    table.emplace("xrCreateFoveationProfileFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateFoveationProfileFB));
    table.emplace("xrDestroyFoveationProfileFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyFoveationProfileFB));
#endif // XRTRANSPORT_EXT_XR_FB_foveation
#ifdef XRTRANSPORT_EXT_XR_FB_hand_tracking_mesh
    table.emplace("xrGetHandMeshFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetHandMeshFB));
#endif // XRTRANSPORT_EXT_XR_FB_hand_tracking_mesh
#ifdef XRTRANSPORT_EXT_XR_FB_haptic_pcm
    table.emplace("xrGetDeviceSampleRateFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetDeviceSampleRateFB));
#endif // XRTRANSPORT_EXT_XR_FB_haptic_pcm
#ifdef XRTRANSPORT_EXT_XR_FB_keyboard_tracking
    table.emplace("xrCreateKeyboardSpaceFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateKeyboardSpaceFB));
    table.emplace("xrQuerySystemTrackedKeyboardFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrQuerySystemTrackedKeyboardFB));
#endif // XRTRANSPORT_EXT_XR_FB_keyboard_tracking
#ifdef XRTRANSPORT_EXT_XR_FB_passthrough
    table.emplace("xrCreateGeometryInstanceFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateGeometryInstanceFB));
    table.emplace("xrCreatePassthroughFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreatePassthroughFB));
    table.emplace("xrCreatePassthroughLayerFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreatePassthroughLayerFB));
    table.emplace("xrDestroyGeometryInstanceFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyGeometryInstanceFB));
    table.emplace("xrDestroyPassthroughFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyPassthroughFB));
    table.emplace("xrDestroyPassthroughLayerFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyPassthroughLayerFB));
    table.emplace("xrGeometryInstanceSetTransformFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGeometryInstanceSetTransformFB));
    table.emplace("xrPassthroughLayerPauseFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPassthroughLayerPauseFB));
    table.emplace("xrPassthroughLayerResumeFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPassthroughLayerResumeFB));
    table.emplace("xrPassthroughLayerSetStyleFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPassthroughLayerSetStyleFB));
    table.emplace("xrPassthroughPauseFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPassthroughPauseFB));
    table.emplace("xrPassthroughStartFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPassthroughStartFB));
#endif // XRTRANSPORT_EXT_XR_FB_passthrough
#ifdef XRTRANSPORT_EXT_XR_FB_passthrough_keyboard_hands
    table.emplace("xrPassthroughLayerSetKeyboardHandsIntensityFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPassthroughLayerSetKeyboardHandsIntensityFB));
#endif // XRTRANSPORT_EXT_XR_FB_passthrough_keyboard_hands
#ifdef XRTRANSPORT_EXT_XR_FB_render_model
    table.emplace("xrEnumerateRenderModelPathsFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateRenderModelPathsFB));
    table.emplace("xrGetRenderModelPropertiesFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetRenderModelPropertiesFB));
    table.emplace("xrLoadRenderModelFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrLoadRenderModelFB));
#endif // XRTRANSPORT_EXT_XR_FB_render_model
#ifdef XRTRANSPORT_EXT_XR_FB_scene
    table.emplace("xrGetSpaceBoundary2DFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpaceBoundary2DFB));
    table.emplace("xrGetSpaceBoundingBox2DFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpaceBoundingBox2DFB));
    table.emplace("xrGetSpaceBoundingBox3DFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpaceBoundingBox3DFB));
    table.emplace("xrGetSpaceRoomLayoutFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpaceRoomLayoutFB));
    table.emplace("xrGetSpaceSemanticLabelsFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpaceSemanticLabelsFB));
#endif // XRTRANSPORT_EXT_XR_FB_scene
#ifdef XRTRANSPORT_EXT_XR_FB_scene_capture
    table.emplace("xrRequestSceneCaptureFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrRequestSceneCaptureFB));
#endif // XRTRANSPORT_EXT_XR_FB_scene_capture
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity
    table.emplace("xrCreateSpatialAnchorFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialAnchorFB));
    table.emplace("xrEnumerateSpaceSupportedComponentsFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateSpaceSupportedComponentsFB));
    table.emplace("xrGetSpaceComponentStatusFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpaceComponentStatusFB));
    table.emplace("xrGetSpaceUuidFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpaceUuidFB));
    table.emplace("xrSetSpaceComponentStatusFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetSpaceComponentStatusFB));
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_container
    table.emplace("xrGetSpaceContainerFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpaceContainerFB));
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_container
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_query
    table.emplace("xrQuerySpacesFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrQuerySpacesFB));
    table.emplace("xrRetrieveSpaceQueryResultsFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrRetrieveSpaceQueryResultsFB));
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_query
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_sharing
    table.emplace("xrShareSpacesFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrShareSpacesFB));
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_sharing
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_storage
    table.emplace("xrEraseSpaceFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEraseSpaceFB));
    table.emplace("xrSaveSpaceFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSaveSpaceFB));
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_storage
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_storage_batch
    table.emplace("xrSaveSpaceListFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSaveSpaceListFB));
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_storage_batch
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_user
    table.emplace("xrCreateSpaceUserFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpaceUserFB));
    table.emplace("xrDestroySpaceUserFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroySpaceUserFB));
    table.emplace("xrGetSpaceUserIdFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpaceUserIdFB));
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_user
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state
    table.emplace("xrGetSwapchainStateFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSwapchainStateFB));
    table.emplace("xrUpdateSwapchainFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrUpdateSwapchainFB));
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state
#ifdef XRTRANSPORT_EXT_XR_FB_triangle_mesh
    table.emplace("xrCreateTriangleMeshFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateTriangleMeshFB));
    table.emplace("xrDestroyTriangleMeshFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyTriangleMeshFB));
    table.emplace("xrTriangleMeshBeginUpdateFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrTriangleMeshBeginUpdateFB));
    table.emplace("xrTriangleMeshBeginVertexBufferUpdateFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrTriangleMeshBeginVertexBufferUpdateFB));
    table.emplace("xrTriangleMeshEndUpdateFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrTriangleMeshEndUpdateFB));
    table.emplace("xrTriangleMeshEndVertexBufferUpdateFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrTriangleMeshEndVertexBufferUpdateFB));
    table.emplace("xrTriangleMeshGetIndexBufferFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrTriangleMeshGetIndexBufferFB));
    table.emplace("xrTriangleMeshGetVertexBufferFB", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrTriangleMeshGetVertexBufferFB));
#endif // XRTRANSPORT_EXT_XR_FB_triangle_mesh
#ifdef XRTRANSPORT_EXT_XR_HTCX_vive_tracker_interaction
    table.emplace("xrEnumerateViveTrackerPathsHTCX", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateViveTrackerPathsHTCX));
#endif // XRTRANSPORT_EXT_XR_HTCX_vive_tracker_interaction
#ifdef XRTRANSPORT_EXT_XR_HTC_anchor
    table.emplace("xrCreateSpatialAnchorHTC", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialAnchorHTC));
    table.emplace("xrGetSpatialAnchorNameHTC", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpatialAnchorNameHTC));
#endif // XRTRANSPORT_EXT_XR_HTC_anchor
#ifdef XRTRANSPORT_EXT_XR_HTC_body_tracking
    table.emplace("xrCreateBodyTrackerHTC", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateBodyTrackerHTC));
    table.emplace("xrDestroyBodyTrackerHTC", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyBodyTrackerHTC));
    table.emplace("xrGetBodySkeletonHTC", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetBodySkeletonHTC));
    table.emplace("xrLocateBodyJointsHTC", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrLocateBodyJointsHTC));
#endif // XRTRANSPORT_EXT_XR_HTC_body_tracking
#ifdef XRTRANSPORT_EXT_XR_HTC_facial_tracking
    table.emplace("xrCreateFacialTrackerHTC", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateFacialTrackerHTC));
    table.emplace("xrDestroyFacialTrackerHTC", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyFacialTrackerHTC));
    table.emplace("xrGetFacialExpressionsHTC", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetFacialExpressionsHTC));
#endif // XRTRANSPORT_EXT_XR_HTC_facial_tracking
#ifdef XRTRANSPORT_EXT_XR_HTC_foveation
    table.emplace("xrApplyFoveationHTC", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrApplyFoveationHTC));
#endif // XRTRANSPORT_EXT_XR_HTC_foveation
#ifdef XRTRANSPORT_EXT_XR_HTC_passthrough
    table.emplace("xrCreatePassthroughHTC", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreatePassthroughHTC));
    table.emplace("xrDestroyPassthroughHTC", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyPassthroughHTC));
#endif // XRTRANSPORT_EXT_XR_HTC_passthrough
#ifdef XRTRANSPORT_EXT_XR_KHR_D3D11_enable
    table.emplace("xrGetD3D11GraphicsRequirementsKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetD3D11GraphicsRequirementsKHR));
#endif // XRTRANSPORT_EXT_XR_KHR_D3D11_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_D3D12_enable
    table.emplace("xrGetD3D12GraphicsRequirementsKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetD3D12GraphicsRequirementsKHR));
#endif // XRTRANSPORT_EXT_XR_KHR_D3D12_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_android_surface_swapchain
    table.emplace("xrCreateSwapchainAndroidSurfaceKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSwapchainAndroidSurfaceKHR));
#endif // XRTRANSPORT_EXT_XR_KHR_android_surface_swapchain
#ifdef XRTRANSPORT_EXT_XR_KHR_android_thread_settings
    table.emplace("xrSetAndroidApplicationThreadKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetAndroidApplicationThreadKHR));
#endif // XRTRANSPORT_EXT_XR_KHR_android_thread_settings
#ifdef XRTRANSPORT_EXT_XR_KHR_convert_timespec_time
    table.emplace("xrConvertTimeToTimespecTimeKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrConvertTimeToTimespecTimeKHR));
    table.emplace("xrConvertTimespecTimeToTimeKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrConvertTimespecTimeToTimeKHR));
#endif // XRTRANSPORT_EXT_XR_KHR_convert_timespec_time
#ifdef XRTRANSPORT_EXT_XR_KHR_extended_struct_name_lengths
    table.emplace("xrStructureTypeToString2KHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStructureTypeToString2KHR));
#endif // XRTRANSPORT_EXT_XR_KHR_extended_struct_name_lengths
#ifdef XRTRANSPORT_EXT_XR_KHR_loader_init
    table.emplace("xrInitializeLoaderKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrInitializeLoaderKHR));
#endif // XRTRANSPORT_EXT_XR_KHR_loader_init
#ifdef XRTRANSPORT_EXT_XR_KHR_metal_enable
    table.emplace("xrGetMetalGraphicsRequirementsKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetMetalGraphicsRequirementsKHR));
#endif // XRTRANSPORT_EXT_XR_KHR_metal_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_opengl_enable
    table.emplace("xrGetOpenGLGraphicsRequirementsKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetOpenGLGraphicsRequirementsKHR));
#endif // XRTRANSPORT_EXT_XR_KHR_opengl_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_opengl_es_enable
    table.emplace("xrGetOpenGLESGraphicsRequirementsKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetOpenGLESGraphicsRequirementsKHR));
#endif // XRTRANSPORT_EXT_XR_KHR_opengl_es_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_visibility_mask
    table.emplace("xrGetVisibilityMaskKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetVisibilityMaskKHR));
#endif // XRTRANSPORT_EXT_XR_KHR_visibility_mask
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_enable
    table.emplace("xrGetVulkanDeviceExtensionsKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetVulkanDeviceExtensionsKHR));
    table.emplace("xrGetVulkanGraphicsDeviceKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetVulkanGraphicsDeviceKHR));
    table.emplace("xrGetVulkanGraphicsRequirementsKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetVulkanGraphicsRequirementsKHR));
    table.emplace("xrGetVulkanInstanceExtensionsKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetVulkanInstanceExtensionsKHR));
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_enable2
    table.emplace("xrCreateVulkanDeviceKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateVulkanDeviceKHR));
    table.emplace("xrCreateVulkanInstanceKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateVulkanInstanceKHR));
    table.emplace("xrGetVulkanGraphicsDevice2KHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetVulkanGraphicsDevice2KHR));
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_enable2
#ifdef XRTRANSPORT_EXT_XR_KHR_win32_convert_performance_counter_time
    table.emplace("xrConvertTimeToWin32PerformanceCounterKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrConvertTimeToWin32PerformanceCounterKHR));
    table.emplace("xrConvertWin32PerformanceCounterToTimeKHR", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrConvertWin32PerformanceCounterToTimeKHR));
#endif // XRTRANSPORT_EXT_XR_KHR_win32_convert_performance_counter_time
#ifdef XRTRANSPORT_EXT_XR_META_colocation_discovery
    table.emplace("xrStartColocationAdvertisementMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStartColocationAdvertisementMETA));
    table.emplace("xrStartColocationDiscoveryMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStartColocationDiscoveryMETA));
    table.emplace("xrStopColocationAdvertisementMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStopColocationAdvertisementMETA));
    table.emplace("xrStopColocationDiscoveryMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStopColocationDiscoveryMETA));
#endif // XRTRANSPORT_EXT_XR_META_colocation_discovery
#ifdef XRTRANSPORT_EXT_XR_META_environment_depth
    table.emplace("xrAcquireEnvironmentDepthImageMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrAcquireEnvironmentDepthImageMETA));
    table.emplace("xrCreateEnvironmentDepthProviderMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateEnvironmentDepthProviderMETA));
    table.emplace("xrCreateEnvironmentDepthSwapchainMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateEnvironmentDepthSwapchainMETA));
    table.emplace("xrDestroyEnvironmentDepthProviderMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyEnvironmentDepthProviderMETA));
    table.emplace("xrDestroyEnvironmentDepthSwapchainMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyEnvironmentDepthSwapchainMETA));
    table.emplace("xrEnumerateEnvironmentDepthSwapchainImagesMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateEnvironmentDepthSwapchainImagesMETA));
    table.emplace("xrGetEnvironmentDepthSwapchainStateMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetEnvironmentDepthSwapchainStateMETA));
    table.emplace("xrSetEnvironmentDepthHandRemovalMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetEnvironmentDepthHandRemovalMETA));
    table.emplace("xrStartEnvironmentDepthProviderMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStartEnvironmentDepthProviderMETA));
    table.emplace("xrStopEnvironmentDepthProviderMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStopEnvironmentDepthProviderMETA));
#endif // XRTRANSPORT_EXT_XR_META_environment_depth
#ifdef XRTRANSPORT_EXT_XR_META_foveation_eye_tracked
    table.emplace("xrGetFoveationEyeTrackedStateMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetFoveationEyeTrackedStateMETA));
#endif // XRTRANSPORT_EXT_XR_META_foveation_eye_tracked
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_color_lut
    table.emplace("xrCreatePassthroughColorLutMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreatePassthroughColorLutMETA));
    table.emplace("xrDestroyPassthroughColorLutMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyPassthroughColorLutMETA));
    table.emplace("xrUpdatePassthroughColorLutMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrUpdatePassthroughColorLutMETA));
#endif // XRTRANSPORT_EXT_XR_META_passthrough_color_lut
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_preferences
    table.emplace("xrGetPassthroughPreferencesMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetPassthroughPreferencesMETA));
#endif // XRTRANSPORT_EXT_XR_META_passthrough_preferences
#ifdef XRTRANSPORT_EXT_XR_META_performance_metrics
    table.emplace("xrEnumeratePerformanceMetricsCounterPathsMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumeratePerformanceMetricsCounterPathsMETA));
    table.emplace("xrGetPerformanceMetricsStateMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetPerformanceMetricsStateMETA));
    table.emplace("xrQueryPerformanceMetricsCounterMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrQueryPerformanceMetricsCounterMETA));
    table.emplace("xrSetPerformanceMetricsStateMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetPerformanceMetricsStateMETA));
#endif // XRTRANSPORT_EXT_XR_META_performance_metrics
#ifdef XRTRANSPORT_EXT_XR_META_recommended_layer_resolution
    table.emplace("xrGetRecommendedLayerResolutionMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetRecommendedLayerResolutionMETA));
#endif // XRTRANSPORT_EXT_XR_META_recommended_layer_resolution
#ifdef XRTRANSPORT_EXT_XR_META_simultaneous_hands_and_controllers
    table.emplace("xrPauseSimultaneousHandsAndControllersTrackingMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPauseSimultaneousHandsAndControllersTrackingMETA));
    table.emplace("xrResumeSimultaneousHandsAndControllersTrackingMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrResumeSimultaneousHandsAndControllersTrackingMETA));
#endif // XRTRANSPORT_EXT_XR_META_simultaneous_hands_and_controllers
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_mesh
    table.emplace("xrGetSpaceTriangleMeshMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpaceTriangleMeshMETA));
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_mesh
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_sharing
    table.emplace("xrShareSpacesMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrShareSpacesMETA));
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_sharing
#ifdef XRTRANSPORT_EXT_XR_META_virtual_keyboard
    table.emplace("xrChangeVirtualKeyboardTextContextMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrChangeVirtualKeyboardTextContextMETA));
    table.emplace("xrCreateVirtualKeyboardMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateVirtualKeyboardMETA));
    table.emplace("xrCreateVirtualKeyboardSpaceMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateVirtualKeyboardSpaceMETA));
    table.emplace("xrDestroyVirtualKeyboardMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyVirtualKeyboardMETA));
    table.emplace("xrGetVirtualKeyboardDirtyTexturesMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetVirtualKeyboardDirtyTexturesMETA));
    table.emplace("xrGetVirtualKeyboardModelAnimationStatesMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetVirtualKeyboardModelAnimationStatesMETA));
    table.emplace("xrGetVirtualKeyboardScaleMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetVirtualKeyboardScaleMETA));
    table.emplace("xrGetVirtualKeyboardTextureDataMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetVirtualKeyboardTextureDataMETA));
    table.emplace("xrSendVirtualKeyboardInputMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSendVirtualKeyboardInputMETA));
    table.emplace("xrSetVirtualKeyboardModelVisibilityMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetVirtualKeyboardModelVisibilityMETA));
    table.emplace("xrSuggestVirtualKeyboardLocationMETA", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSuggestVirtualKeyboardLocationMETA));
#endif // XRTRANSPORT_EXT_XR_META_virtual_keyboard
#ifdef XRTRANSPORT_EXT_XR_ML_compat
    table.emplace("xrCreateSpaceFromCoordinateFrameUIDML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpaceFromCoordinateFrameUIDML));
#endif // XRTRANSPORT_EXT_XR_ML_compat
#ifdef XRTRANSPORT_EXT_XR_ML_facial_expression
    table.emplace("xrCreateFacialExpressionClientML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateFacialExpressionClientML));
    table.emplace("xrDestroyFacialExpressionClientML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyFacialExpressionClientML));
    table.emplace("xrGetFacialExpressionBlendShapePropertiesML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetFacialExpressionBlendShapePropertiesML));
#endif // XRTRANSPORT_EXT_XR_ML_facial_expression
#ifdef XRTRANSPORT_EXT_XR_ML_localization_map
    table.emplace("xrCreateExportedLocalizationMapML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateExportedLocalizationMapML));
    table.emplace("xrDestroyExportedLocalizationMapML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyExportedLocalizationMapML));
    table.emplace("xrEnableLocalizationEventsML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnableLocalizationEventsML));
    table.emplace("xrGetExportedLocalizationMapDataML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetExportedLocalizationMapDataML));
    table.emplace("xrImportLocalizationMapML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrImportLocalizationMapML));
    table.emplace("xrQueryLocalizationMapsML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrQueryLocalizationMapsML));
    table.emplace("xrRequestMapLocalizationML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrRequestMapLocalizationML));
#endif // XRTRANSPORT_EXT_XR_ML_localization_map
#ifdef XRTRANSPORT_EXT_XR_ML_marker_understanding
    table.emplace("xrCreateMarkerDetectorML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateMarkerDetectorML));
    table.emplace("xrCreateMarkerSpaceML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateMarkerSpaceML));
    table.emplace("xrDestroyMarkerDetectorML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyMarkerDetectorML));
    table.emplace("xrGetMarkerDetectorStateML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetMarkerDetectorStateML));
    table.emplace("xrGetMarkerLengthML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetMarkerLengthML));
    table.emplace("xrGetMarkerNumberML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetMarkerNumberML));
    table.emplace("xrGetMarkerReprojectionErrorML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetMarkerReprojectionErrorML));
    table.emplace("xrGetMarkerStringML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetMarkerStringML));
    table.emplace("xrGetMarkersML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetMarkersML));
    table.emplace("xrSnapshotMarkerDetectorML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSnapshotMarkerDetectorML));
#endif // XRTRANSPORT_EXT_XR_ML_marker_understanding
#ifdef XRTRANSPORT_EXT_XR_ML_spatial_anchors
    table.emplace("xrCreateSpatialAnchorsAsyncML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialAnchorsAsyncML));
    table.emplace("xrCreateSpatialAnchorsCompleteML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialAnchorsCompleteML));
    table.emplace("xrGetSpatialAnchorStateML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpatialAnchorStateML));
#endif // XRTRANSPORT_EXT_XR_ML_spatial_anchors
#ifdef XRTRANSPORT_EXT_XR_ML_spatial_anchors_storage
    table.emplace("xrCreateSpatialAnchorsStorageML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialAnchorsStorageML));
    table.emplace("xrDeleteSpatialAnchorsAsyncML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDeleteSpatialAnchorsAsyncML));
    table.emplace("xrDeleteSpatialAnchorsCompleteML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDeleteSpatialAnchorsCompleteML));
    table.emplace("xrDestroySpatialAnchorsStorageML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroySpatialAnchorsStorageML));
    table.emplace("xrPublishSpatialAnchorsAsyncML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPublishSpatialAnchorsAsyncML));
    table.emplace("xrPublishSpatialAnchorsCompleteML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPublishSpatialAnchorsCompleteML));
    table.emplace("xrQuerySpatialAnchorsAsyncML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrQuerySpatialAnchorsAsyncML));
    table.emplace("xrQuerySpatialAnchorsCompleteML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrQuerySpatialAnchorsCompleteML));
    table.emplace("xrUpdateSpatialAnchorsExpirationAsyncML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrUpdateSpatialAnchorsExpirationAsyncML));
    table.emplace("xrUpdateSpatialAnchorsExpirationCompleteML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrUpdateSpatialAnchorsExpirationCompleteML));
#endif // XRTRANSPORT_EXT_XR_ML_spatial_anchors_storage
#ifdef XRTRANSPORT_EXT_XR_ML_system_notifications
    table.emplace("xrSetSystemNotificationsML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetSystemNotificationsML));
#endif // XRTRANSPORT_EXT_XR_ML_system_notifications
#ifdef XRTRANSPORT_EXT_XR_ML_user_calibration
    table.emplace("xrEnableUserCalibrationEventsML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnableUserCalibrationEventsML));
#endif // XRTRANSPORT_EXT_XR_ML_user_calibration
#ifdef XRTRANSPORT_EXT_XR_ML_world_mesh_detection
    table.emplace("xrAllocateWorldMeshBufferML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrAllocateWorldMeshBufferML));
    table.emplace("xrCreateWorldMeshDetectorML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateWorldMeshDetectorML));
    table.emplace("xrDestroyWorldMeshDetectorML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyWorldMeshDetectorML));
    table.emplace("xrFreeWorldMeshBufferML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrFreeWorldMeshBufferML));
    table.emplace("xrGetWorldMeshBufferRecommendSizeML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetWorldMeshBufferRecommendSizeML));
    table.emplace("xrRequestWorldMeshAsyncML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrRequestWorldMeshAsyncML));
    table.emplace("xrRequestWorldMeshCompleteML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrRequestWorldMeshCompleteML));
    table.emplace("xrRequestWorldMeshStateAsyncML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrRequestWorldMeshStateAsyncML));
    table.emplace("xrRequestWorldMeshStateCompleteML", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrRequestWorldMeshStateCompleteML));
#endif // XRTRANSPORT_EXT_XR_ML_world_mesh_detection
#ifdef XRTRANSPORT_EXT_XR_MNDX_force_feedback_curl
    table.emplace("xrApplyForceFeedbackCurlMNDX", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrApplyForceFeedbackCurlMNDX));
#endif // XRTRANSPORT_EXT_XR_MNDX_force_feedback_curl
#ifdef XRTRANSPORT_EXT_XR_MSFT_composition_layer_reprojection
    table.emplace("xrEnumerateReprojectionModesMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateReprojectionModesMSFT));
#endif // XRTRANSPORT_EXT_XR_MSFT_composition_layer_reprojection
#ifdef XRTRANSPORT_EXT_XR_MSFT_controller_model
    table.emplace("xrGetControllerModelKeyMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetControllerModelKeyMSFT));
    table.emplace("xrGetControllerModelPropertiesMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetControllerModelPropertiesMSFT));
    table.emplace("xrGetControllerModelStateMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetControllerModelStateMSFT));
    table.emplace("xrLoadControllerModelMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrLoadControllerModelMSFT));
#endif // XRTRANSPORT_EXT_XR_MSFT_controller_model
#ifdef XRTRANSPORT_EXT_XR_MSFT_hand_tracking_mesh
    table.emplace("xrCreateHandMeshSpaceMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateHandMeshSpaceMSFT));
    table.emplace("xrUpdateHandMeshMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrUpdateHandMeshMSFT));
#endif // XRTRANSPORT_EXT_XR_MSFT_hand_tracking_mesh
#ifdef XRTRANSPORT_EXT_XR_MSFT_perception_anchor_interop
    table.emplace("xrCreateSpatialAnchorFromPerceptionAnchorMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialAnchorFromPerceptionAnchorMSFT));
    table.emplace("xrTryGetPerceptionAnchorFromSpatialAnchorMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrTryGetPerceptionAnchorFromSpatialAnchorMSFT));
#endif // XRTRANSPORT_EXT_XR_MSFT_perception_anchor_interop
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_marker
    table.emplace("xrGetSceneMarkerDecodedStringMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSceneMarkerDecodedStringMSFT));
    table.emplace("xrGetSceneMarkerRawDataMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSceneMarkerRawDataMSFT));
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_marker
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_understanding
    table.emplace("xrComputeNewSceneMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrComputeNewSceneMSFT));
    table.emplace("xrCreateSceneMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSceneMSFT));
    table.emplace("xrCreateSceneObserverMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSceneObserverMSFT));
    table.emplace("xrDestroySceneMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroySceneMSFT));
    table.emplace("xrDestroySceneObserverMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroySceneObserverMSFT));
    table.emplace("xrEnumerateSceneComputeFeaturesMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateSceneComputeFeaturesMSFT));
    table.emplace("xrGetSceneComponentsMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSceneComponentsMSFT));
    table.emplace("xrGetSceneComputeStateMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSceneComputeStateMSFT));
    table.emplace("xrGetSceneMeshBuffersMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSceneMeshBuffersMSFT));
    table.emplace("xrLocateSceneComponentsMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrLocateSceneComponentsMSFT));
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_understanding
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_understanding_serialization
    table.emplace("xrDeserializeSceneMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDeserializeSceneMSFT));
    table.emplace("xrGetSerializedSceneFragmentDataMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSerializedSceneFragmentDataMSFT));
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_understanding_serialization
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_anchor
    table.emplace("xrCreateSpatialAnchorMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialAnchorMSFT));
    table.emplace("xrCreateSpatialAnchorSpaceMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialAnchorSpaceMSFT));
    table.emplace("xrDestroySpatialAnchorMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroySpatialAnchorMSFT));
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_anchor
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_anchor_persistence
    table.emplace("xrClearSpatialAnchorStoreMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrClearSpatialAnchorStoreMSFT));
    table.emplace("xrCreateSpatialAnchorFromPersistedNameMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialAnchorFromPersistedNameMSFT));
    table.emplace("xrCreateSpatialAnchorStoreConnectionMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialAnchorStoreConnectionMSFT));
    table.emplace("xrDestroySpatialAnchorStoreConnectionMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroySpatialAnchorStoreConnectionMSFT));
    table.emplace("xrEnumeratePersistedSpatialAnchorNamesMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumeratePersistedSpatialAnchorNamesMSFT));
    table.emplace("xrPersistSpatialAnchorMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPersistSpatialAnchorMSFT));
    table.emplace("xrUnpersistSpatialAnchorMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrUnpersistSpatialAnchorMSFT));
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_anchor_persistence
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_graph_bridge
    table.emplace("xrCreateSpatialGraphNodeSpaceMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSpatialGraphNodeSpaceMSFT));
    table.emplace("xrDestroySpatialGraphNodeBindingMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroySpatialGraphNodeBindingMSFT));
    table.emplace("xrGetSpatialGraphNodeBindingPropertiesMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSpatialGraphNodeBindingPropertiesMSFT));
    table.emplace("xrTryCreateSpatialGraphStaticNodeBindingMSFT", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrTryCreateSpatialGraphStaticNodeBindingMSFT));
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_graph_bridge
#ifdef XRTRANSPORT_EXT_XR_OCULUS_audio_device_guid
    table.emplace("xrGetAudioInputDeviceGuidOculus", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetAudioInputDeviceGuidOculus));
    table.emplace("xrGetAudioOutputDeviceGuidOculus", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetAudioOutputDeviceGuidOculus));
#endif // XRTRANSPORT_EXT_XR_OCULUS_audio_device_guid
#ifdef XRTRANSPORT_EXT_XR_OCULUS_external_camera
    table.emplace("xrEnumerateExternalCamerasOCULUS", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateExternalCamerasOCULUS));
#endif // XRTRANSPORT_EXT_XR_OCULUS_external_camera
#ifdef XRTRANSPORT_EXT_XR_QCOM_tracking_optimization_settings
    table.emplace("xrSetTrackingOptimizationSettingsHintQCOM", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetTrackingOptimizationSettingsHintQCOM));
#endif // XRTRANSPORT_EXT_XR_QCOM_tracking_optimization_settings
#ifdef XRTRANSPORT_EXT_XR_VARJO_environment_depth_estimation
    table.emplace("xrSetEnvironmentDepthEstimationVARJO", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetEnvironmentDepthEstimationVARJO));
#endif // XRTRANSPORT_EXT_XR_VARJO_environment_depth_estimation
#ifdef XRTRANSPORT_EXT_XR_VARJO_marker_tracking
    table.emplace("xrCreateMarkerSpaceVARJO", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateMarkerSpaceVARJO));
    table.emplace("xrGetMarkerSizeVARJO", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetMarkerSizeVARJO));
    table.emplace("xrSetMarkerTrackingPredictionVARJO", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetMarkerTrackingPredictionVARJO));
    table.emplace("xrSetMarkerTrackingTimeoutVARJO", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetMarkerTrackingTimeoutVARJO));
    table.emplace("xrSetMarkerTrackingVARJO", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetMarkerTrackingVARJO));
#endif // XRTRANSPORT_EXT_XR_VARJO_marker_tracking
#ifdef XRTRANSPORT_EXT_XR_VARJO_view_offset
    table.emplace("xrSetViewOffsetVARJO", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSetViewOffsetVARJO));
#endif // XRTRANSPORT_EXT_XR_VARJO_view_offset
    table.emplace("xrAcquireSwapchainImage", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrAcquireSwapchainImage));
    table.emplace("xrApplyHapticFeedback", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrApplyHapticFeedback));
    table.emplace("xrAttachSessionActionSets", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrAttachSessionActionSets));
    table.emplace("xrBeginFrame", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrBeginFrame));
    table.emplace("xrBeginSession", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrBeginSession));
    table.emplace("xrCreateAction", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateAction));
    table.emplace("xrCreateActionSet", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateActionSet));
    table.emplace("xrCreateActionSpace", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateActionSpace));
    table.emplace("xrCreateInstance", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateInstance));
    table.emplace("xrCreateReferenceSpace", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateReferenceSpace));
    table.emplace("xrCreateSession", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSession));
    table.emplace("xrCreateSwapchain", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrCreateSwapchain));
    table.emplace("xrDestroyAction", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyAction));
    table.emplace("xrDestroyActionSet", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyActionSet));
    table.emplace("xrDestroyInstance", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroyInstance));
    table.emplace("xrDestroySession", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroySession));
    table.emplace("xrDestroySpace", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroySpace));
    table.emplace("xrDestroySwapchain", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrDestroySwapchain));
    table.emplace("xrEndFrame", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEndFrame));
    table.emplace("xrEndSession", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEndSession));
    table.emplace("xrEnumerateApiLayerProperties", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateApiLayerProperties));
    table.emplace("xrEnumerateBoundSourcesForAction", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateBoundSourcesForAction));
    table.emplace("xrEnumerateEnvironmentBlendModes", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateEnvironmentBlendModes));
    table.emplace("xrEnumerateInstanceExtensionProperties", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateInstanceExtensionProperties));
    table.emplace("xrEnumerateReferenceSpaces", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateReferenceSpaces));
    table.emplace("xrEnumerateSwapchainFormats", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateSwapchainFormats));
    table.emplace("xrEnumerateSwapchainImages", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateSwapchainImages));
    table.emplace("xrEnumerateViewConfigurationViews", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateViewConfigurationViews));
    table.emplace("xrEnumerateViewConfigurations", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrEnumerateViewConfigurations));
    table.emplace("xrGetActionStateBoolean", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetActionStateBoolean));
    table.emplace("xrGetActionStateFloat", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetActionStateFloat));
    table.emplace("xrGetActionStatePose", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetActionStatePose));
    table.emplace("xrGetActionStateVector2f", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetActionStateVector2f));
    table.emplace("xrGetCurrentInteractionProfile", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetCurrentInteractionProfile));
    table.emplace("xrGetInputSourceLocalizedName", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetInputSourceLocalizedName));
    table.emplace("xrGetInstanceProperties", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetInstanceProperties));
    table.emplace("xrGetReferenceSpaceBoundsRect", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetReferenceSpaceBoundsRect));
    table.emplace("xrGetSystem", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSystem));
    table.emplace("xrGetSystemProperties", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetSystemProperties));
    table.emplace("xrGetViewConfigurationProperties", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrGetViewConfigurationProperties));
    table.emplace("xrLocateSpace", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrLocateSpace));
    table.emplace("xrLocateSpaces", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrLocateSpaces));
    table.emplace("xrLocateViews", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrLocateViews));
    table.emplace("xrPathToString", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPathToString));
    table.emplace("xrPollEvent", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrPollEvent));
    table.emplace("xrReleaseSwapchainImage", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrReleaseSwapchainImage));
    table.emplace("xrRequestExitSession", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrRequestExitSession));
    table.emplace("xrResultToString", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrResultToString));
    table.emplace("xrStopHapticFeedback", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStopHapticFeedback));
    table.emplace("xrStringToPath", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStringToPath));
    table.emplace("xrStructureTypeToString", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrStructureTypeToString));
    table.emplace("xrSuggestInteractionProfileBindings", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSuggestInteractionProfileBindings));
    table.emplace("xrSyncActions", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrSyncActions));
    table.emplace("xrWaitFrame", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrWaitFrame));
    table.emplace("xrWaitSwapchainImage", reinterpret_cast<PFN_xrVoidFunction>(rpc::xrWaitSwapchainImage));

}

} // namespace xrtransport