/*
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file was automatically generated by the code_generation module.
 * Any changes made to this file will be lost when regenerated.
 *
 * To modify this file, edit the corresponding template in:
 * code_generation/templates/server/function_loader.mako
 */
// SPDX-License-Identifier: LGPL-3.0-or-later

#ifndef XRTRANSPORT_FUNCTION_LOADER_H
#define XRTRANSPORT_FUNCTION_LOADER_H

#include "openxr/openxr.h"

#include <stdexcept>
#include <string>

namespace xrtransport {

class FunctionLoaderException : public std::runtime_error {
public:
    explicit FunctionLoaderException(const std::string& message) : std::runtime_error(message) {}
};

class FunctionLoader {
public:
    explicit FunctionLoader(PFN_xrGetInstanceProcAddr pfn_xrGetInstanceProcAddr) :
        loader_instance(XR_NULL_HANDLE),
        GetInstanceProcAddr(pfn_xrGetInstanceProcAddr)
    {}

    // Used by ensure_function_loaded to load XR functions
    // Starts as XR_NULL_HANDLE but must be set once an instance is created
    // so that it can be used to fetch functions.
    XrInstance loader_instance;

    // used to load functions
    PFN_xrGetInstanceProcAddr GetInstanceProcAddr;

#ifdef XRTRANSPORT_EXT_XR_ALMALENCE_digital_lens_control
    PFN_xrSetDigitalLensControlALMALENCE SetDigitalLensControlALMALENCE = nullptr;
#endif // XRTRANSPORT_EXT_XR_ALMALENCE_digital_lens_control
#ifdef XRTRANSPORT_EXT_XR_BD_body_tracking
    PFN_xrCreateBodyTrackerBD CreateBodyTrackerBD = nullptr;
    PFN_xrDestroyBodyTrackerBD DestroyBodyTrackerBD = nullptr;
    PFN_xrLocateBodyJointsBD LocateBodyJointsBD = nullptr;
#endif // XRTRANSPORT_EXT_XR_BD_body_tracking
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_anchor
    PFN_xrCreateSpatialAnchorAsyncBD CreateSpatialAnchorAsyncBD = nullptr;
    PFN_xrCreateSpatialAnchorCompleteBD CreateSpatialAnchorCompleteBD = nullptr;
    PFN_xrPersistSpatialAnchorAsyncBD PersistSpatialAnchorAsyncBD = nullptr;
    PFN_xrPersistSpatialAnchorCompleteBD PersistSpatialAnchorCompleteBD = nullptr;
    PFN_xrUnpersistSpatialAnchorAsyncBD UnpersistSpatialAnchorAsyncBD = nullptr;
    PFN_xrUnpersistSpatialAnchorCompleteBD UnpersistSpatialAnchorCompleteBD = nullptr;
#endif // XRTRANSPORT_EXT_XR_BD_spatial_anchor
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_anchor_sharing
    PFN_xrDownloadSharedSpatialAnchorAsyncBD DownloadSharedSpatialAnchorAsyncBD = nullptr;
    PFN_xrDownloadSharedSpatialAnchorCompleteBD DownloadSharedSpatialAnchorCompleteBD = nullptr;
    PFN_xrShareSpatialAnchorAsyncBD ShareSpatialAnchorAsyncBD = nullptr;
    PFN_xrShareSpatialAnchorCompleteBD ShareSpatialAnchorCompleteBD = nullptr;
#endif // XRTRANSPORT_EXT_XR_BD_spatial_anchor_sharing
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_scene
    PFN_xrCaptureSceneAsyncBD CaptureSceneAsyncBD = nullptr;
    PFN_xrCaptureSceneCompleteBD CaptureSceneCompleteBD = nullptr;
#endif // XRTRANSPORT_EXT_XR_BD_spatial_scene
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_sensing
    PFN_xrCreateAnchorSpaceBD CreateAnchorSpaceBD = nullptr;
    PFN_xrCreateSenseDataProviderBD CreateSenseDataProviderBD = nullptr;
    PFN_xrCreateSpatialEntityAnchorBD CreateSpatialEntityAnchorBD = nullptr;
    PFN_xrDestroyAnchorBD DestroyAnchorBD = nullptr;
    PFN_xrDestroySenseDataProviderBD DestroySenseDataProviderBD = nullptr;
    PFN_xrDestroySenseDataSnapshotBD DestroySenseDataSnapshotBD = nullptr;
    PFN_xrEnumerateSpatialEntityComponentTypesBD EnumerateSpatialEntityComponentTypesBD = nullptr;
    PFN_xrGetAnchorUuidBD GetAnchorUuidBD = nullptr;
    PFN_xrGetQueriedSenseDataBD GetQueriedSenseDataBD = nullptr;
    PFN_xrGetSenseDataProviderStateBD GetSenseDataProviderStateBD = nullptr;
    PFN_xrGetSpatialEntityComponentDataBD GetSpatialEntityComponentDataBD = nullptr;
    PFN_xrGetSpatialEntityUuidBD GetSpatialEntityUuidBD = nullptr;
    PFN_xrQuerySenseDataAsyncBD QuerySenseDataAsyncBD = nullptr;
    PFN_xrQuerySenseDataCompleteBD QuerySenseDataCompleteBD = nullptr;
    PFN_xrStartSenseDataProviderAsyncBD StartSenseDataProviderAsyncBD = nullptr;
    PFN_xrStartSenseDataProviderCompleteBD StartSenseDataProviderCompleteBD = nullptr;
    PFN_xrStopSenseDataProviderBD StopSenseDataProviderBD = nullptr;
#endif // XRTRANSPORT_EXT_XR_BD_spatial_sensing
#ifdef XRTRANSPORT_EXT_XR_EXT_conformance_automation
    PFN_xrSetInputDeviceActiveEXT SetInputDeviceActiveEXT = nullptr;
    PFN_xrSetInputDeviceLocationEXT SetInputDeviceLocationEXT = nullptr;
    PFN_xrSetInputDeviceStateBoolEXT SetInputDeviceStateBoolEXT = nullptr;
    PFN_xrSetInputDeviceStateFloatEXT SetInputDeviceStateFloatEXT = nullptr;
    PFN_xrSetInputDeviceStateVector2fEXT SetInputDeviceStateVector2fEXT = nullptr;
#endif // XRTRANSPORT_EXT_XR_EXT_conformance_automation
#ifdef XRTRANSPORT_EXT_XR_EXT_debug_utils
    PFN_xrCreateDebugUtilsMessengerEXT CreateDebugUtilsMessengerEXT = nullptr;
    PFN_xrDestroyDebugUtilsMessengerEXT DestroyDebugUtilsMessengerEXT = nullptr;
    PFN_xrSessionBeginDebugUtilsLabelRegionEXT SessionBeginDebugUtilsLabelRegionEXT = nullptr;
    PFN_xrSessionEndDebugUtilsLabelRegionEXT SessionEndDebugUtilsLabelRegionEXT = nullptr;
    PFN_xrSessionInsertDebugUtilsLabelEXT SessionInsertDebugUtilsLabelEXT = nullptr;
    PFN_xrSetDebugUtilsObjectNameEXT SetDebugUtilsObjectNameEXT = nullptr;
    PFN_xrSubmitDebugUtilsMessageEXT SubmitDebugUtilsMessageEXT = nullptr;
#endif // XRTRANSPORT_EXT_XR_EXT_debug_utils
#ifdef XRTRANSPORT_EXT_XR_EXT_future
    PFN_xrCancelFutureEXT CancelFutureEXT = nullptr;
    PFN_xrPollFutureEXT PollFutureEXT = nullptr;
#endif // XRTRANSPORT_EXT_XR_EXT_future
#ifdef XRTRANSPORT_EXT_XR_EXT_hand_tracking
    PFN_xrCreateHandTrackerEXT CreateHandTrackerEXT = nullptr;
    PFN_xrDestroyHandTrackerEXT DestroyHandTrackerEXT = nullptr;
    PFN_xrLocateHandJointsEXT LocateHandJointsEXT = nullptr;
#endif // XRTRANSPORT_EXT_XR_EXT_hand_tracking
#ifdef XRTRANSPORT_EXT_XR_EXT_performance_settings
    PFN_xrPerfSettingsSetPerformanceLevelEXT PerfSettingsSetPerformanceLevelEXT = nullptr;
#endif // XRTRANSPORT_EXT_XR_EXT_performance_settings
#ifdef XRTRANSPORT_EXT_XR_EXT_plane_detection
    PFN_xrBeginPlaneDetectionEXT BeginPlaneDetectionEXT = nullptr;
    PFN_xrCreatePlaneDetectorEXT CreatePlaneDetectorEXT = nullptr;
    PFN_xrDestroyPlaneDetectorEXT DestroyPlaneDetectorEXT = nullptr;
    PFN_xrGetPlaneDetectionStateEXT GetPlaneDetectionStateEXT = nullptr;
    PFN_xrGetPlaneDetectionsEXT GetPlaneDetectionsEXT = nullptr;
    PFN_xrGetPlanePolygonBufferEXT GetPlanePolygonBufferEXT = nullptr;
#endif // XRTRANSPORT_EXT_XR_EXT_plane_detection
#ifdef XRTRANSPORT_EXT_XR_EXT_thermal_query
    PFN_xrThermalGetTemperatureTrendEXT ThermalGetTemperatureTrendEXT = nullptr;
#endif // XRTRANSPORT_EXT_XR_EXT_thermal_query
#ifdef XRTRANSPORT_EXT_XR_FB_body_tracking
    PFN_xrCreateBodyTrackerFB CreateBodyTrackerFB = nullptr;
    PFN_xrDestroyBodyTrackerFB DestroyBodyTrackerFB = nullptr;
    PFN_xrGetBodySkeletonFB GetBodySkeletonFB = nullptr;
    PFN_xrLocateBodyJointsFB LocateBodyJointsFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_body_tracking
#ifdef XRTRANSPORT_EXT_XR_FB_color_space
    PFN_xrEnumerateColorSpacesFB EnumerateColorSpacesFB = nullptr;
    PFN_xrSetColorSpaceFB SetColorSpaceFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_color_space
#ifdef XRTRANSPORT_EXT_XR_FB_display_refresh_rate
    PFN_xrEnumerateDisplayRefreshRatesFB EnumerateDisplayRefreshRatesFB = nullptr;
    PFN_xrGetDisplayRefreshRateFB GetDisplayRefreshRateFB = nullptr;
    PFN_xrRequestDisplayRefreshRateFB RequestDisplayRefreshRateFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_display_refresh_rate
#ifdef XRTRANSPORT_EXT_XR_FB_eye_tracking_social
    PFN_xrCreateEyeTrackerFB CreateEyeTrackerFB = nullptr;
    PFN_xrDestroyEyeTrackerFB DestroyEyeTrackerFB = nullptr;
    PFN_xrGetEyeGazesFB GetEyeGazesFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_eye_tracking_social
#ifdef XRTRANSPORT_EXT_XR_FB_face_tracking
    PFN_xrCreateFaceTrackerFB CreateFaceTrackerFB = nullptr;
    PFN_xrDestroyFaceTrackerFB DestroyFaceTrackerFB = nullptr;
    PFN_xrGetFaceExpressionWeightsFB GetFaceExpressionWeightsFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_face_tracking
#ifdef XRTRANSPORT_EXT_XR_FB_face_tracking2
    PFN_xrCreateFaceTracker2FB CreateFaceTracker2FB = nullptr;
    PFN_xrDestroyFaceTracker2FB DestroyFaceTracker2FB = nullptr;
    PFN_xrGetFaceExpressionWeights2FB GetFaceExpressionWeights2FB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_face_tracking2
#ifdef XRTRANSPORT_EXT_XR_FB_foveation
    PFN_xrCreateFoveationProfileFB CreateFoveationProfileFB = nullptr;
    PFN_xrDestroyFoveationProfileFB DestroyFoveationProfileFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_foveation
#ifdef XRTRANSPORT_EXT_XR_FB_hand_tracking_mesh
    PFN_xrGetHandMeshFB GetHandMeshFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_hand_tracking_mesh
#ifdef XRTRANSPORT_EXT_XR_FB_haptic_pcm
    PFN_xrGetDeviceSampleRateFB GetDeviceSampleRateFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_haptic_pcm
#ifdef XRTRANSPORT_EXT_XR_FB_keyboard_tracking
    PFN_xrCreateKeyboardSpaceFB CreateKeyboardSpaceFB = nullptr;
    PFN_xrQuerySystemTrackedKeyboardFB QuerySystemTrackedKeyboardFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_keyboard_tracking
#ifdef XRTRANSPORT_EXT_XR_FB_passthrough
    PFN_xrCreateGeometryInstanceFB CreateGeometryInstanceFB = nullptr;
    PFN_xrCreatePassthroughFB CreatePassthroughFB = nullptr;
    PFN_xrCreatePassthroughLayerFB CreatePassthroughLayerFB = nullptr;
    PFN_xrDestroyGeometryInstanceFB DestroyGeometryInstanceFB = nullptr;
    PFN_xrDestroyPassthroughFB DestroyPassthroughFB = nullptr;
    PFN_xrDestroyPassthroughLayerFB DestroyPassthroughLayerFB = nullptr;
    PFN_xrGeometryInstanceSetTransformFB GeometryInstanceSetTransformFB = nullptr;
    PFN_xrPassthroughLayerPauseFB PassthroughLayerPauseFB = nullptr;
    PFN_xrPassthroughLayerResumeFB PassthroughLayerResumeFB = nullptr;
    PFN_xrPassthroughLayerSetStyleFB PassthroughLayerSetStyleFB = nullptr;
    PFN_xrPassthroughPauseFB PassthroughPauseFB = nullptr;
    PFN_xrPassthroughStartFB PassthroughStartFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_passthrough
#ifdef XRTRANSPORT_EXT_XR_FB_passthrough_keyboard_hands
    PFN_xrPassthroughLayerSetKeyboardHandsIntensityFB PassthroughLayerSetKeyboardHandsIntensityFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_passthrough_keyboard_hands
#ifdef XRTRANSPORT_EXT_XR_FB_render_model
    PFN_xrEnumerateRenderModelPathsFB EnumerateRenderModelPathsFB = nullptr;
    PFN_xrGetRenderModelPropertiesFB GetRenderModelPropertiesFB = nullptr;
    PFN_xrLoadRenderModelFB LoadRenderModelFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_render_model
#ifdef XRTRANSPORT_EXT_XR_FB_scene
    PFN_xrGetSpaceBoundary2DFB GetSpaceBoundary2DFB = nullptr;
    PFN_xrGetSpaceBoundingBox2DFB GetSpaceBoundingBox2DFB = nullptr;
    PFN_xrGetSpaceBoundingBox3DFB GetSpaceBoundingBox3DFB = nullptr;
    PFN_xrGetSpaceRoomLayoutFB GetSpaceRoomLayoutFB = nullptr;
    PFN_xrGetSpaceSemanticLabelsFB GetSpaceSemanticLabelsFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_scene
#ifdef XRTRANSPORT_EXT_XR_FB_scene_capture
    PFN_xrRequestSceneCaptureFB RequestSceneCaptureFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_scene_capture
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity
    PFN_xrCreateSpatialAnchorFB CreateSpatialAnchorFB = nullptr;
    PFN_xrEnumerateSpaceSupportedComponentsFB EnumerateSpaceSupportedComponentsFB = nullptr;
    PFN_xrGetSpaceComponentStatusFB GetSpaceComponentStatusFB = nullptr;
    PFN_xrGetSpaceUuidFB GetSpaceUuidFB = nullptr;
    PFN_xrSetSpaceComponentStatusFB SetSpaceComponentStatusFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_container
    PFN_xrGetSpaceContainerFB GetSpaceContainerFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_container
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_query
    PFN_xrQuerySpacesFB QuerySpacesFB = nullptr;
    PFN_xrRetrieveSpaceQueryResultsFB RetrieveSpaceQueryResultsFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_query
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_sharing
    PFN_xrShareSpacesFB ShareSpacesFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_sharing
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_storage
    PFN_xrEraseSpaceFB EraseSpaceFB = nullptr;
    PFN_xrSaveSpaceFB SaveSpaceFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_storage
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_storage_batch
    PFN_xrSaveSpaceListFB SaveSpaceListFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_storage_batch
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_user
    PFN_xrCreateSpaceUserFB CreateSpaceUserFB = nullptr;
    PFN_xrDestroySpaceUserFB DestroySpaceUserFB = nullptr;
    PFN_xrGetSpaceUserIdFB GetSpaceUserIdFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_user
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state
    PFN_xrGetSwapchainStateFB GetSwapchainStateFB = nullptr;
    PFN_xrUpdateSwapchainFB UpdateSwapchainFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state
#ifdef XRTRANSPORT_EXT_XR_FB_triangle_mesh
    PFN_xrCreateTriangleMeshFB CreateTriangleMeshFB = nullptr;
    PFN_xrDestroyTriangleMeshFB DestroyTriangleMeshFB = nullptr;
    PFN_xrTriangleMeshBeginUpdateFB TriangleMeshBeginUpdateFB = nullptr;
    PFN_xrTriangleMeshBeginVertexBufferUpdateFB TriangleMeshBeginVertexBufferUpdateFB = nullptr;
    PFN_xrTriangleMeshEndUpdateFB TriangleMeshEndUpdateFB = nullptr;
    PFN_xrTriangleMeshEndVertexBufferUpdateFB TriangleMeshEndVertexBufferUpdateFB = nullptr;
    PFN_xrTriangleMeshGetIndexBufferFB TriangleMeshGetIndexBufferFB = nullptr;
    PFN_xrTriangleMeshGetVertexBufferFB TriangleMeshGetVertexBufferFB = nullptr;
#endif // XRTRANSPORT_EXT_XR_FB_triangle_mesh
#ifdef XRTRANSPORT_EXT_XR_HTCX_vive_tracker_interaction
    PFN_xrEnumerateViveTrackerPathsHTCX EnumerateViveTrackerPathsHTCX = nullptr;
#endif // XRTRANSPORT_EXT_XR_HTCX_vive_tracker_interaction
#ifdef XRTRANSPORT_EXT_XR_HTC_anchor
    PFN_xrCreateSpatialAnchorHTC CreateSpatialAnchorHTC = nullptr;
    PFN_xrGetSpatialAnchorNameHTC GetSpatialAnchorNameHTC = nullptr;
#endif // XRTRANSPORT_EXT_XR_HTC_anchor
#ifdef XRTRANSPORT_EXT_XR_HTC_body_tracking
    PFN_xrCreateBodyTrackerHTC CreateBodyTrackerHTC = nullptr;
    PFN_xrDestroyBodyTrackerHTC DestroyBodyTrackerHTC = nullptr;
    PFN_xrGetBodySkeletonHTC GetBodySkeletonHTC = nullptr;
    PFN_xrLocateBodyJointsHTC LocateBodyJointsHTC = nullptr;
#endif // XRTRANSPORT_EXT_XR_HTC_body_tracking
#ifdef XRTRANSPORT_EXT_XR_HTC_facial_tracking
    PFN_xrCreateFacialTrackerHTC CreateFacialTrackerHTC = nullptr;
    PFN_xrDestroyFacialTrackerHTC DestroyFacialTrackerHTC = nullptr;
    PFN_xrGetFacialExpressionsHTC GetFacialExpressionsHTC = nullptr;
#endif // XRTRANSPORT_EXT_XR_HTC_facial_tracking
#ifdef XRTRANSPORT_EXT_XR_HTC_foveation
    PFN_xrApplyFoveationHTC ApplyFoveationHTC = nullptr;
#endif // XRTRANSPORT_EXT_XR_HTC_foveation
#ifdef XRTRANSPORT_EXT_XR_HTC_passthrough
    PFN_xrCreatePassthroughHTC CreatePassthroughHTC = nullptr;
    PFN_xrDestroyPassthroughHTC DestroyPassthroughHTC = nullptr;
#endif // XRTRANSPORT_EXT_XR_HTC_passthrough
#ifdef XRTRANSPORT_EXT_XR_KHR_D3D11_enable
    PFN_xrGetD3D11GraphicsRequirementsKHR GetD3D11GraphicsRequirementsKHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_D3D11_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_D3D12_enable
    PFN_xrGetD3D12GraphicsRequirementsKHR GetD3D12GraphicsRequirementsKHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_D3D12_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_android_surface_swapchain
    PFN_xrCreateSwapchainAndroidSurfaceKHR CreateSwapchainAndroidSurfaceKHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_android_surface_swapchain
#ifdef XRTRANSPORT_EXT_XR_KHR_android_thread_settings
    PFN_xrSetAndroidApplicationThreadKHR SetAndroidApplicationThreadKHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_android_thread_settings
#ifdef XRTRANSPORT_EXT_XR_KHR_convert_timespec_time
    PFN_xrConvertTimeToTimespecTimeKHR ConvertTimeToTimespecTimeKHR = nullptr;
    PFN_xrConvertTimespecTimeToTimeKHR ConvertTimespecTimeToTimeKHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_convert_timespec_time
#ifdef XRTRANSPORT_EXT_XR_KHR_extended_struct_name_lengths
    PFN_xrStructureTypeToString2KHR StructureTypeToString2KHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_extended_struct_name_lengths
#ifdef XRTRANSPORT_EXT_XR_KHR_loader_init
    PFN_xrInitializeLoaderKHR InitializeLoaderKHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_loader_init
#ifdef XRTRANSPORT_EXT_XR_KHR_metal_enable
    PFN_xrGetMetalGraphicsRequirementsKHR GetMetalGraphicsRequirementsKHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_metal_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_opengl_enable
    PFN_xrGetOpenGLGraphicsRequirementsKHR GetOpenGLGraphicsRequirementsKHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_opengl_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_opengl_es_enable
    PFN_xrGetOpenGLESGraphicsRequirementsKHR GetOpenGLESGraphicsRequirementsKHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_opengl_es_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_visibility_mask
    PFN_xrGetVisibilityMaskKHR GetVisibilityMaskKHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_visibility_mask
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_enable
    PFN_xrGetVulkanDeviceExtensionsKHR GetVulkanDeviceExtensionsKHR = nullptr;
    PFN_xrGetVulkanGraphicsDeviceKHR GetVulkanGraphicsDeviceKHR = nullptr;
    PFN_xrGetVulkanGraphicsRequirementsKHR GetVulkanGraphicsRequirementsKHR = nullptr;
    PFN_xrGetVulkanInstanceExtensionsKHR GetVulkanInstanceExtensionsKHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_enable2
    PFN_xrCreateVulkanDeviceKHR CreateVulkanDeviceKHR = nullptr;
    PFN_xrCreateVulkanInstanceKHR CreateVulkanInstanceKHR = nullptr;
    PFN_xrGetVulkanGraphicsDevice2KHR GetVulkanGraphicsDevice2KHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_enable2
#ifdef XRTRANSPORT_EXT_XR_KHR_win32_convert_performance_counter_time
    PFN_xrConvertTimeToWin32PerformanceCounterKHR ConvertTimeToWin32PerformanceCounterKHR = nullptr;
    PFN_xrConvertWin32PerformanceCounterToTimeKHR ConvertWin32PerformanceCounterToTimeKHR = nullptr;
#endif // XRTRANSPORT_EXT_XR_KHR_win32_convert_performance_counter_time
#ifdef XRTRANSPORT_EXT_XR_META_colocation_discovery
    PFN_xrStartColocationAdvertisementMETA StartColocationAdvertisementMETA = nullptr;
    PFN_xrStartColocationDiscoveryMETA StartColocationDiscoveryMETA = nullptr;
    PFN_xrStopColocationAdvertisementMETA StopColocationAdvertisementMETA = nullptr;
    PFN_xrStopColocationDiscoveryMETA StopColocationDiscoveryMETA = nullptr;
#endif // XRTRANSPORT_EXT_XR_META_colocation_discovery
#ifdef XRTRANSPORT_EXT_XR_META_environment_depth
    PFN_xrAcquireEnvironmentDepthImageMETA AcquireEnvironmentDepthImageMETA = nullptr;
    PFN_xrCreateEnvironmentDepthProviderMETA CreateEnvironmentDepthProviderMETA = nullptr;
    PFN_xrCreateEnvironmentDepthSwapchainMETA CreateEnvironmentDepthSwapchainMETA = nullptr;
    PFN_xrDestroyEnvironmentDepthProviderMETA DestroyEnvironmentDepthProviderMETA = nullptr;
    PFN_xrDestroyEnvironmentDepthSwapchainMETA DestroyEnvironmentDepthSwapchainMETA = nullptr;
    PFN_xrEnumerateEnvironmentDepthSwapchainImagesMETA EnumerateEnvironmentDepthSwapchainImagesMETA = nullptr;
    PFN_xrGetEnvironmentDepthSwapchainStateMETA GetEnvironmentDepthSwapchainStateMETA = nullptr;
    PFN_xrSetEnvironmentDepthHandRemovalMETA SetEnvironmentDepthHandRemovalMETA = nullptr;
    PFN_xrStartEnvironmentDepthProviderMETA StartEnvironmentDepthProviderMETA = nullptr;
    PFN_xrStopEnvironmentDepthProviderMETA StopEnvironmentDepthProviderMETA = nullptr;
#endif // XRTRANSPORT_EXT_XR_META_environment_depth
#ifdef XRTRANSPORT_EXT_XR_META_foveation_eye_tracked
    PFN_xrGetFoveationEyeTrackedStateMETA GetFoveationEyeTrackedStateMETA = nullptr;
#endif // XRTRANSPORT_EXT_XR_META_foveation_eye_tracked
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_color_lut
    PFN_xrCreatePassthroughColorLutMETA CreatePassthroughColorLutMETA = nullptr;
    PFN_xrDestroyPassthroughColorLutMETA DestroyPassthroughColorLutMETA = nullptr;
    PFN_xrUpdatePassthroughColorLutMETA UpdatePassthroughColorLutMETA = nullptr;
#endif // XRTRANSPORT_EXT_XR_META_passthrough_color_lut
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_preferences
    PFN_xrGetPassthroughPreferencesMETA GetPassthroughPreferencesMETA = nullptr;
#endif // XRTRANSPORT_EXT_XR_META_passthrough_preferences
#ifdef XRTRANSPORT_EXT_XR_META_performance_metrics
    PFN_xrEnumeratePerformanceMetricsCounterPathsMETA EnumeratePerformanceMetricsCounterPathsMETA = nullptr;
    PFN_xrGetPerformanceMetricsStateMETA GetPerformanceMetricsStateMETA = nullptr;
    PFN_xrQueryPerformanceMetricsCounterMETA QueryPerformanceMetricsCounterMETA = nullptr;
    PFN_xrSetPerformanceMetricsStateMETA SetPerformanceMetricsStateMETA = nullptr;
#endif // XRTRANSPORT_EXT_XR_META_performance_metrics
#ifdef XRTRANSPORT_EXT_XR_META_recommended_layer_resolution
    PFN_xrGetRecommendedLayerResolutionMETA GetRecommendedLayerResolutionMETA = nullptr;
#endif // XRTRANSPORT_EXT_XR_META_recommended_layer_resolution
#ifdef XRTRANSPORT_EXT_XR_META_simultaneous_hands_and_controllers
    PFN_xrPauseSimultaneousHandsAndControllersTrackingMETA PauseSimultaneousHandsAndControllersTrackingMETA = nullptr;
    PFN_xrResumeSimultaneousHandsAndControllersTrackingMETA ResumeSimultaneousHandsAndControllersTrackingMETA = nullptr;
#endif // XRTRANSPORT_EXT_XR_META_simultaneous_hands_and_controllers
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_mesh
    PFN_xrGetSpaceTriangleMeshMETA GetSpaceTriangleMeshMETA = nullptr;
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_mesh
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_sharing
    PFN_xrShareSpacesMETA ShareSpacesMETA = nullptr;
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_sharing
#ifdef XRTRANSPORT_EXT_XR_META_virtual_keyboard
    PFN_xrChangeVirtualKeyboardTextContextMETA ChangeVirtualKeyboardTextContextMETA = nullptr;
    PFN_xrCreateVirtualKeyboardMETA CreateVirtualKeyboardMETA = nullptr;
    PFN_xrCreateVirtualKeyboardSpaceMETA CreateVirtualKeyboardSpaceMETA = nullptr;
    PFN_xrDestroyVirtualKeyboardMETA DestroyVirtualKeyboardMETA = nullptr;
    PFN_xrGetVirtualKeyboardDirtyTexturesMETA GetVirtualKeyboardDirtyTexturesMETA = nullptr;
    PFN_xrGetVirtualKeyboardModelAnimationStatesMETA GetVirtualKeyboardModelAnimationStatesMETA = nullptr;
    PFN_xrGetVirtualKeyboardScaleMETA GetVirtualKeyboardScaleMETA = nullptr;
    PFN_xrGetVirtualKeyboardTextureDataMETA GetVirtualKeyboardTextureDataMETA = nullptr;
    PFN_xrSendVirtualKeyboardInputMETA SendVirtualKeyboardInputMETA = nullptr;
    PFN_xrSetVirtualKeyboardModelVisibilityMETA SetVirtualKeyboardModelVisibilityMETA = nullptr;
    PFN_xrSuggestVirtualKeyboardLocationMETA SuggestVirtualKeyboardLocationMETA = nullptr;
#endif // XRTRANSPORT_EXT_XR_META_virtual_keyboard
#ifdef XRTRANSPORT_EXT_XR_ML_compat
    PFN_xrCreateSpaceFromCoordinateFrameUIDML CreateSpaceFromCoordinateFrameUIDML = nullptr;
#endif // XRTRANSPORT_EXT_XR_ML_compat
#ifdef XRTRANSPORT_EXT_XR_ML_facial_expression
    PFN_xrCreateFacialExpressionClientML CreateFacialExpressionClientML = nullptr;
    PFN_xrDestroyFacialExpressionClientML DestroyFacialExpressionClientML = nullptr;
    PFN_xrGetFacialExpressionBlendShapePropertiesML GetFacialExpressionBlendShapePropertiesML = nullptr;
#endif // XRTRANSPORT_EXT_XR_ML_facial_expression
#ifdef XRTRANSPORT_EXT_XR_ML_localization_map
    PFN_xrCreateExportedLocalizationMapML CreateExportedLocalizationMapML = nullptr;
    PFN_xrDestroyExportedLocalizationMapML DestroyExportedLocalizationMapML = nullptr;
    PFN_xrEnableLocalizationEventsML EnableLocalizationEventsML = nullptr;
    PFN_xrGetExportedLocalizationMapDataML GetExportedLocalizationMapDataML = nullptr;
    PFN_xrImportLocalizationMapML ImportLocalizationMapML = nullptr;
    PFN_xrQueryLocalizationMapsML QueryLocalizationMapsML = nullptr;
    PFN_xrRequestMapLocalizationML RequestMapLocalizationML = nullptr;
#endif // XRTRANSPORT_EXT_XR_ML_localization_map
#ifdef XRTRANSPORT_EXT_XR_ML_marker_understanding
    PFN_xrCreateMarkerDetectorML CreateMarkerDetectorML = nullptr;
    PFN_xrCreateMarkerSpaceML CreateMarkerSpaceML = nullptr;
    PFN_xrDestroyMarkerDetectorML DestroyMarkerDetectorML = nullptr;
    PFN_xrGetMarkerDetectorStateML GetMarkerDetectorStateML = nullptr;
    PFN_xrGetMarkerLengthML GetMarkerLengthML = nullptr;
    PFN_xrGetMarkerNumberML GetMarkerNumberML = nullptr;
    PFN_xrGetMarkerReprojectionErrorML GetMarkerReprojectionErrorML = nullptr;
    PFN_xrGetMarkerStringML GetMarkerStringML = nullptr;
    PFN_xrGetMarkersML GetMarkersML = nullptr;
    PFN_xrSnapshotMarkerDetectorML SnapshotMarkerDetectorML = nullptr;
#endif // XRTRANSPORT_EXT_XR_ML_marker_understanding
#ifdef XRTRANSPORT_EXT_XR_ML_spatial_anchors
    PFN_xrCreateSpatialAnchorsAsyncML CreateSpatialAnchorsAsyncML = nullptr;
    PFN_xrCreateSpatialAnchorsCompleteML CreateSpatialAnchorsCompleteML = nullptr;
    PFN_xrGetSpatialAnchorStateML GetSpatialAnchorStateML = nullptr;
#endif // XRTRANSPORT_EXT_XR_ML_spatial_anchors
#ifdef XRTRANSPORT_EXT_XR_ML_spatial_anchors_storage
    PFN_xrCreateSpatialAnchorsStorageML CreateSpatialAnchorsStorageML = nullptr;
    PFN_xrDeleteSpatialAnchorsAsyncML DeleteSpatialAnchorsAsyncML = nullptr;
    PFN_xrDeleteSpatialAnchorsCompleteML DeleteSpatialAnchorsCompleteML = nullptr;
    PFN_xrDestroySpatialAnchorsStorageML DestroySpatialAnchorsStorageML = nullptr;
    PFN_xrPublishSpatialAnchorsAsyncML PublishSpatialAnchorsAsyncML = nullptr;
    PFN_xrPublishSpatialAnchorsCompleteML PublishSpatialAnchorsCompleteML = nullptr;
    PFN_xrQuerySpatialAnchorsAsyncML QuerySpatialAnchorsAsyncML = nullptr;
    PFN_xrQuerySpatialAnchorsCompleteML QuerySpatialAnchorsCompleteML = nullptr;
    PFN_xrUpdateSpatialAnchorsExpirationAsyncML UpdateSpatialAnchorsExpirationAsyncML = nullptr;
    PFN_xrUpdateSpatialAnchorsExpirationCompleteML UpdateSpatialAnchorsExpirationCompleteML = nullptr;
#endif // XRTRANSPORT_EXT_XR_ML_spatial_anchors_storage
#ifdef XRTRANSPORT_EXT_XR_ML_system_notifications
    PFN_xrSetSystemNotificationsML SetSystemNotificationsML = nullptr;
#endif // XRTRANSPORT_EXT_XR_ML_system_notifications
#ifdef XRTRANSPORT_EXT_XR_ML_user_calibration
    PFN_xrEnableUserCalibrationEventsML EnableUserCalibrationEventsML = nullptr;
#endif // XRTRANSPORT_EXT_XR_ML_user_calibration
#ifdef XRTRANSPORT_EXT_XR_ML_world_mesh_detection
    PFN_xrAllocateWorldMeshBufferML AllocateWorldMeshBufferML = nullptr;
    PFN_xrCreateWorldMeshDetectorML CreateWorldMeshDetectorML = nullptr;
    PFN_xrDestroyWorldMeshDetectorML DestroyWorldMeshDetectorML = nullptr;
    PFN_xrFreeWorldMeshBufferML FreeWorldMeshBufferML = nullptr;
    PFN_xrGetWorldMeshBufferRecommendSizeML GetWorldMeshBufferRecommendSizeML = nullptr;
    PFN_xrRequestWorldMeshAsyncML RequestWorldMeshAsyncML = nullptr;
    PFN_xrRequestWorldMeshCompleteML RequestWorldMeshCompleteML = nullptr;
    PFN_xrRequestWorldMeshStateAsyncML RequestWorldMeshStateAsyncML = nullptr;
    PFN_xrRequestWorldMeshStateCompleteML RequestWorldMeshStateCompleteML = nullptr;
#endif // XRTRANSPORT_EXT_XR_ML_world_mesh_detection
#ifdef XRTRANSPORT_EXT_XR_MNDX_force_feedback_curl
    PFN_xrApplyForceFeedbackCurlMNDX ApplyForceFeedbackCurlMNDX = nullptr;
#endif // XRTRANSPORT_EXT_XR_MNDX_force_feedback_curl
#ifdef XRTRANSPORT_EXT_XR_MSFT_composition_layer_reprojection
    PFN_xrEnumerateReprojectionModesMSFT EnumerateReprojectionModesMSFT = nullptr;
#endif // XRTRANSPORT_EXT_XR_MSFT_composition_layer_reprojection
#ifdef XRTRANSPORT_EXT_XR_MSFT_controller_model
    PFN_xrGetControllerModelKeyMSFT GetControllerModelKeyMSFT = nullptr;
    PFN_xrGetControllerModelPropertiesMSFT GetControllerModelPropertiesMSFT = nullptr;
    PFN_xrGetControllerModelStateMSFT GetControllerModelStateMSFT = nullptr;
    PFN_xrLoadControllerModelMSFT LoadControllerModelMSFT = nullptr;
#endif // XRTRANSPORT_EXT_XR_MSFT_controller_model
#ifdef XRTRANSPORT_EXT_XR_MSFT_hand_tracking_mesh
    PFN_xrCreateHandMeshSpaceMSFT CreateHandMeshSpaceMSFT = nullptr;
    PFN_xrUpdateHandMeshMSFT UpdateHandMeshMSFT = nullptr;
#endif // XRTRANSPORT_EXT_XR_MSFT_hand_tracking_mesh
#ifdef XRTRANSPORT_EXT_XR_MSFT_perception_anchor_interop
    PFN_xrCreateSpatialAnchorFromPerceptionAnchorMSFT CreateSpatialAnchorFromPerceptionAnchorMSFT = nullptr;
    PFN_xrTryGetPerceptionAnchorFromSpatialAnchorMSFT TryGetPerceptionAnchorFromSpatialAnchorMSFT = nullptr;
#endif // XRTRANSPORT_EXT_XR_MSFT_perception_anchor_interop
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_marker
    PFN_xrGetSceneMarkerDecodedStringMSFT GetSceneMarkerDecodedStringMSFT = nullptr;
    PFN_xrGetSceneMarkerRawDataMSFT GetSceneMarkerRawDataMSFT = nullptr;
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_marker
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_understanding
    PFN_xrComputeNewSceneMSFT ComputeNewSceneMSFT = nullptr;
    PFN_xrCreateSceneMSFT CreateSceneMSFT = nullptr;
    PFN_xrCreateSceneObserverMSFT CreateSceneObserverMSFT = nullptr;
    PFN_xrDestroySceneMSFT DestroySceneMSFT = nullptr;
    PFN_xrDestroySceneObserverMSFT DestroySceneObserverMSFT = nullptr;
    PFN_xrEnumerateSceneComputeFeaturesMSFT EnumerateSceneComputeFeaturesMSFT = nullptr;
    PFN_xrGetSceneComponentsMSFT GetSceneComponentsMSFT = nullptr;
    PFN_xrGetSceneComputeStateMSFT GetSceneComputeStateMSFT = nullptr;
    PFN_xrGetSceneMeshBuffersMSFT GetSceneMeshBuffersMSFT = nullptr;
    PFN_xrLocateSceneComponentsMSFT LocateSceneComponentsMSFT = nullptr;
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_understanding
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_understanding_serialization
    PFN_xrDeserializeSceneMSFT DeserializeSceneMSFT = nullptr;
    PFN_xrGetSerializedSceneFragmentDataMSFT GetSerializedSceneFragmentDataMSFT = nullptr;
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_understanding_serialization
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_anchor
    PFN_xrCreateSpatialAnchorMSFT CreateSpatialAnchorMSFT = nullptr;
    PFN_xrCreateSpatialAnchorSpaceMSFT CreateSpatialAnchorSpaceMSFT = nullptr;
    PFN_xrDestroySpatialAnchorMSFT DestroySpatialAnchorMSFT = nullptr;
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_anchor
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_anchor_persistence
    PFN_xrClearSpatialAnchorStoreMSFT ClearSpatialAnchorStoreMSFT = nullptr;
    PFN_xrCreateSpatialAnchorFromPersistedNameMSFT CreateSpatialAnchorFromPersistedNameMSFT = nullptr;
    PFN_xrCreateSpatialAnchorStoreConnectionMSFT CreateSpatialAnchorStoreConnectionMSFT = nullptr;
    PFN_xrDestroySpatialAnchorStoreConnectionMSFT DestroySpatialAnchorStoreConnectionMSFT = nullptr;
    PFN_xrEnumeratePersistedSpatialAnchorNamesMSFT EnumeratePersistedSpatialAnchorNamesMSFT = nullptr;
    PFN_xrPersistSpatialAnchorMSFT PersistSpatialAnchorMSFT = nullptr;
    PFN_xrUnpersistSpatialAnchorMSFT UnpersistSpatialAnchorMSFT = nullptr;
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_anchor_persistence
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_graph_bridge
    PFN_xrCreateSpatialGraphNodeSpaceMSFT CreateSpatialGraphNodeSpaceMSFT = nullptr;
    PFN_xrDestroySpatialGraphNodeBindingMSFT DestroySpatialGraphNodeBindingMSFT = nullptr;
    PFN_xrGetSpatialGraphNodeBindingPropertiesMSFT GetSpatialGraphNodeBindingPropertiesMSFT = nullptr;
    PFN_xrTryCreateSpatialGraphStaticNodeBindingMSFT TryCreateSpatialGraphStaticNodeBindingMSFT = nullptr;
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_graph_bridge
#ifdef XRTRANSPORT_EXT_XR_OCULUS_audio_device_guid
    PFN_xrGetAudioInputDeviceGuidOculus GetAudioInputDeviceGuidOculus = nullptr;
    PFN_xrGetAudioOutputDeviceGuidOculus GetAudioOutputDeviceGuidOculus = nullptr;
#endif // XRTRANSPORT_EXT_XR_OCULUS_audio_device_guid
#ifdef XRTRANSPORT_EXT_XR_OCULUS_external_camera
    PFN_xrEnumerateExternalCamerasOCULUS EnumerateExternalCamerasOCULUS = nullptr;
#endif // XRTRANSPORT_EXT_XR_OCULUS_external_camera
#ifdef XRTRANSPORT_EXT_XR_QCOM_tracking_optimization_settings
    PFN_xrSetTrackingOptimizationSettingsHintQCOM SetTrackingOptimizationSettingsHintQCOM = nullptr;
#endif // XRTRANSPORT_EXT_XR_QCOM_tracking_optimization_settings
#ifdef XRTRANSPORT_EXT_XR_VARJO_environment_depth_estimation
    PFN_xrSetEnvironmentDepthEstimationVARJO SetEnvironmentDepthEstimationVARJO = nullptr;
#endif // XRTRANSPORT_EXT_XR_VARJO_environment_depth_estimation
#ifdef XRTRANSPORT_EXT_XR_VARJO_marker_tracking
    PFN_xrCreateMarkerSpaceVARJO CreateMarkerSpaceVARJO = nullptr;
    PFN_xrGetMarkerSizeVARJO GetMarkerSizeVARJO = nullptr;
    PFN_xrSetMarkerTrackingPredictionVARJO SetMarkerTrackingPredictionVARJO = nullptr;
    PFN_xrSetMarkerTrackingTimeoutVARJO SetMarkerTrackingTimeoutVARJO = nullptr;
    PFN_xrSetMarkerTrackingVARJO SetMarkerTrackingVARJO = nullptr;
#endif // XRTRANSPORT_EXT_XR_VARJO_marker_tracking
#ifdef XRTRANSPORT_EXT_XR_VARJO_view_offset
    PFN_xrSetViewOffsetVARJO SetViewOffsetVARJO = nullptr;
#endif // XRTRANSPORT_EXT_XR_VARJO_view_offset
    PFN_xrAcquireSwapchainImage AcquireSwapchainImage = nullptr;
    PFN_xrApplyHapticFeedback ApplyHapticFeedback = nullptr;
    PFN_xrAttachSessionActionSets AttachSessionActionSets = nullptr;
    PFN_xrBeginFrame BeginFrame = nullptr;
    PFN_xrBeginSession BeginSession = nullptr;
    PFN_xrCreateAction CreateAction = nullptr;
    PFN_xrCreateActionSet CreateActionSet = nullptr;
    PFN_xrCreateActionSpace CreateActionSpace = nullptr;
    PFN_xrCreateInstance CreateInstance = nullptr;
    PFN_xrCreateReferenceSpace CreateReferenceSpace = nullptr;
    PFN_xrCreateSession CreateSession = nullptr;
    PFN_xrCreateSwapchain CreateSwapchain = nullptr;
    PFN_xrDestroyAction DestroyAction = nullptr;
    PFN_xrDestroyActionSet DestroyActionSet = nullptr;
    PFN_xrDestroyInstance DestroyInstance = nullptr;
    PFN_xrDestroySession DestroySession = nullptr;
    PFN_xrDestroySpace DestroySpace = nullptr;
    PFN_xrDestroySwapchain DestroySwapchain = nullptr;
    PFN_xrEndFrame EndFrame = nullptr;
    PFN_xrEndSession EndSession = nullptr;
    PFN_xrEnumerateApiLayerProperties EnumerateApiLayerProperties = nullptr;
    PFN_xrEnumerateBoundSourcesForAction EnumerateBoundSourcesForAction = nullptr;
    PFN_xrEnumerateEnvironmentBlendModes EnumerateEnvironmentBlendModes = nullptr;
    PFN_xrEnumerateInstanceExtensionProperties EnumerateInstanceExtensionProperties = nullptr;
    PFN_xrEnumerateReferenceSpaces EnumerateReferenceSpaces = nullptr;
    PFN_xrEnumerateSwapchainFormats EnumerateSwapchainFormats = nullptr;
    PFN_xrEnumerateSwapchainImages EnumerateSwapchainImages = nullptr;
    PFN_xrEnumerateViewConfigurationViews EnumerateViewConfigurationViews = nullptr;
    PFN_xrEnumerateViewConfigurations EnumerateViewConfigurations = nullptr;
    PFN_xrGetActionStateBoolean GetActionStateBoolean = nullptr;
    PFN_xrGetActionStateFloat GetActionStateFloat = nullptr;
    PFN_xrGetActionStatePose GetActionStatePose = nullptr;
    PFN_xrGetActionStateVector2f GetActionStateVector2f = nullptr;
    PFN_xrGetCurrentInteractionProfile GetCurrentInteractionProfile = nullptr;
    PFN_xrGetInputSourceLocalizedName GetInputSourceLocalizedName = nullptr;
    PFN_xrGetInstanceProperties GetInstanceProperties = nullptr;
    PFN_xrGetReferenceSpaceBoundsRect GetReferenceSpaceBoundsRect = nullptr;
    PFN_xrGetSystem GetSystem = nullptr;
    PFN_xrGetSystemProperties GetSystemProperties = nullptr;
    PFN_xrGetViewConfigurationProperties GetViewConfigurationProperties = nullptr;
    PFN_xrLocateSpace LocateSpace = nullptr;
    PFN_xrLocateSpaces LocateSpaces = nullptr;
    PFN_xrLocateViews LocateViews = nullptr;
    PFN_xrPathToString PathToString = nullptr;
    PFN_xrPollEvent PollEvent = nullptr;
    PFN_xrReleaseSwapchainImage ReleaseSwapchainImage = nullptr;
    PFN_xrRequestExitSession RequestExitSession = nullptr;
    PFN_xrResultToString ResultToString = nullptr;
    PFN_xrStopHapticFeedback StopHapticFeedback = nullptr;
    PFN_xrStringToPath StringToPath = nullptr;
    PFN_xrStructureTypeToString StructureTypeToString = nullptr;
    PFN_xrSuggestInteractionProfileBindings SuggestInteractionProfileBindings = nullptr;
    PFN_xrSyncActions SyncActions = nullptr;
    PFN_xrWaitFrame WaitFrame = nullptr;
    PFN_xrWaitSwapchainImage WaitSwapchainImage = nullptr;


    // defined inline in header so that it can be used by server modules
    template <typename FuncPtr,
            typename = std::enable_if_t<
                std::is_pointer_v<FuncPtr> &&
                std::is_function_v<std::remove_pointer_t<FuncPtr>>
            >>
    void ensure_function_loaded(const char* name, FuncPtr& function) const {
        if (*function != nullptr) {
            // function is already loaded, do nothing
            return;
        }

        XrResult result = GetInstanceProcAddr(loader_instance, name, reinterpret_cast<PFN_xrVoidFunction*>(&function));

        if (!XR_SUCCEEDED(result)) {
            throw FunctionLoaderException("xrGetInstanceProcAddr for " + std::string(name) + " returned an error: " + std::to_string(result));
        }
    }
};

} // namespace xrtransport

#endif // XRTRANSPORT_FUNCTION_LOADER_H